version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pdfjs-dist"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      all-npm:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-pip:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
