// This file is auto-generated by @hey-api/openapi-ts

export const AccessTokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
    },
    expires: {
      type: "string",
      format: "date-time",
      title: "Expires",
    },
  },
  type: "object",
  required: ["access_token", "token_type", "expires"],
  title: "AccessToken",
  description: "API access token.",
} as const;

export const AnnotationResponseSchema = {
  properties: {
    page: {
      type: "integer",
      title: "Page",
    },
    body: {
      type: "string",
      title: "Body",
    },
    color: {
      type: "string",
      title: "Color",
    },
    excerpt: {
      type: "string",
      title: "Excerpt",
    },
    rects: {
      items: {
        $ref: "#/components/schemas/NormalizedRect",
      },
      type: "array",
      title: "Rects",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Label",
      description: "User-set identifier, used to cross-reference.",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    author_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Author Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    author_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Author Name",
    },
  },
  type: "object",
  required: ["page", "body", "color", "excerpt", "rects", "id", "created_at"],
  title: "AnnotationResponse",
} as const;

export const ApiKeyCreateRequestSchema = {
  properties: {
    description: {
      type: "string",
      title: "Description",
    },
    expires_at: {
      type: "string",
      format: "date-time",
      title: "Expires At",
    },
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    scopes: {
      $ref: "#/components/schemas/Scopes",
    },
  },
  type: "object",
  required: ["description", "expires_at", "user_id", "scopes"],
  title: "ApiKeyCreateRequest",
} as const;

export const ApiKeyCreateResultResponseSchema = {
  properties: {
    token: {
      type: "string",
      title: "Token",
    },
    expires_at: {
      type: "string",
      format: "date-time",
      title: "Expires At",
    },
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
  },
  type: "object",
  required: ["token", "expires_at", "user_id"],
  title: "ApiKeyCreateResultResponse",
} as const;

export const ApiKeyResetRequestSchema = {
  properties: {
    expires_at: {
      type: "string",
      format: "date-time",
      title: "Expires At",
    },
  },
  type: "object",
  required: ["expires_at"],
  title: "ApiKeyResetRequest",
} as const;

export const ApiKeyResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    description: {
      type: "string",
      title: "Description",
    },
    expires_at: {
      type: "string",
      format: "date-time",
      title: "Expires At",
    },
    is_revoked: {
      type: "boolean",
      title: "Is Revoked",
    },
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    scopes: {
      $ref: "#/components/schemas/Scopes",
    },
    user: {
      anyOf: [
        {
          $ref: "#/components/schemas/UserSummaryResponse",
        },
        {
          type: "null",
        },
      ],
    },
    scopes_str: {
      type: "string",
      title: "Scopes Str",
      readOnly: true,
    },
    is_expired: {
      type: "boolean",
      title: "Is Expired",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "description",
    "expires_at",
    "is_revoked",
    "user_id",
    "scopes",
    "scopes_str",
    "is_expired",
  ],
  title: "ApiKeyResponse",
} as const;

export const AppStateResponseSchema = {
  properties: {
    is_initial_user_created: {
      type: "boolean",
      title: "Is Initial User Created",
      default: false,
    },
    sso_servers: {
      items: {
        $ref: "#/components/schemas/SsoConfigResponse",
      },
      type: "array",
      title: "Sso Servers",
    },
    auto_login_sso_server: {
      anyOf: [
        {
          $ref: "#/components/schemas/SsoConfigResponse",
        },
        {
          type: "null",
        },
      ],
    },
    is_setup_complete: {
      type: "boolean",
      title: "Is Setup Complete",
      description: "Check if the setup is complete",
      readOnly: true,
    },
  },
  type: "object",
  required: ["is_setup_complete"],
  title: "AppStateResponse",
} as const;

export const AssignmentResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    user: {
      $ref: "#/components/schemas/UserSummaryResponse",
    },
    inherited_from: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Inherited From",
    },
    permission: {
      type: "string",
      enum: ["owner", "read", "modify"],
      title: "Permission",
    },
    is_read_only_by_current_user: {
      type: "boolean",
      title: "Is Read Only By Current User",
      description: "Whether current user can only read this assignment",
      readOnly: true,
    },
  },
  type: "object",
  required: ["id", "user", "permission", "is_read_only_by_current_user"],
  title: "AssignmentResponse",
} as const;

export const AuthProviderOidcCreateRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["name"],
  title: "AuthProviderOidcCreateRequest",
} as const;

export const AuthProviderOidcResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    entity_type: {
      type: "string",
      const: "OIDC",
      title: "Entity Type",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
    client_id: {
      type: "string",
      title: "Client Id",
    },
    client_secret: {
      type: "string",
      title: "Client Secret",
    },
    group_claim_name: {
      type: "string",
      title: "Group Claim Name",
    },
    auto_discovery_url: {
      type: "string",
      title: "Auto Discovery Url",
    },
    additional_scopes: {
      type: "string",
      title: "Additional Scopes",
    },
    auto_login: {
      type: "boolean",
      title: "Auto Login",
    },
    group_claim_rules: {
      items: {
        $ref: "#/components/schemas/OidcGroupRule-Output",
      },
      type: "array",
      title: "Group Claim Rules",
    },
    redirect_url: {
      type: "string",
      title: "Redirect Url",
      description:
        "URL to which the OIDC provider will redirect after successful authentication",
    },
    authorize_url: {
      type: "string",
      title: "Authorize Url",
      description:
        "URL to which the frontend should redirect the user to initiate OIDC authentication",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "entity_type",
    "is_enabled",
    "is_protected",
    "client_id",
    "client_secret",
    "group_claim_name",
    "auto_discovery_url",
    "additional_scopes",
    "auto_login",
    "group_claim_rules",
    "redirect_url",
    "authorize_url",
  ],
  title: "AuthProviderOidcResponse",
} as const;

export const AuthProviderOidcUpdateRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
      default: false,
    },
    client_id: {
      type: "string",
      title: "Client Id",
    },
    auto_discovery_url: {
      type: "string",
      maxLength: 2083,
      minLength: 1,
      format: "uri",
      title: "Auto Discovery Url",
    },
    additional_scopes: {
      type: "string",
      minLength: 0,
      title: "Additional Scopes",
      default: "",
    },
    group_claim_name: {
      type: "string",
      title: "Group Claim Name",
      default: "groups",
    },
    group_claim_rules: {
      items: {
        $ref: "#/components/schemas/OidcGroupRule-Input",
      },
      type: "array",
      title: "Group Claim Rules",
    },
    auto_login: {
      type: "boolean",
      title: "Auto Login",
      default: false,
    },
  },
  type: "object",
  required: ["name", "client_id", "auto_discovery_url"],
  title: "AuthProviderOidcUpdateRequest",
} as const;

export const AuthProviderResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
  },
  type: "object",
  required: ["id", "name", "entity_type", "is_enabled", "is_protected"],
  title: "AuthProviderResponse",
  description:
    "Generic response model for authentication providers.\n\nSpecific provider types may have additional parameters, but all share these common parameters.",
} as const;

export const Body_CreateAuthTokenSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: "string",
          pattern: "^password$",
        },
        {
          type: "null",
        },
      ],
      title: "Grant Type",
    },
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
    },
    scope: {
      type: "string",
      title: "Scope",
      default: "",
    },
    client_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Id",
    },
    client_secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      format: "password",
      title: "Client Secret",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "Body_CreateAuthToken",
} as const;

export const Body_UploadFileSchema = {
  properties: {
    file: {
      type: "string",
      contentMediaType: "application/octet-stream",
      title: "File",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    collection_id: {
      type: "string",
      format: "uuid",
      title: "Collection Id",
    },
    tags: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags",
    },
  },
  type: "object",
  required: ["file", "name", "collection_id"],
  title: "Body_UploadFile",
} as const;

export const CollectionResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    entity_type: {
      type: "string",
      enum: ["folder", "group"],
      title: "Entity Type",
    },
  },
  type: "object",
  required: ["id", "name", "entity_type"],
  title: "CollectionResponse",
} as const;

export const CollectionWithDetailsResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    entity_type: {
      type: "string",
      enum: ["folder", "group"],
      title: "Entity Type",
    },
    files: {
      items: {
        $ref: "#/components/schemas/FileResponse",
      },
      type: "array",
      title: "Files",
    },
    owner: {
      $ref: "#/components/schemas/UserSummaryResponse",
    },
    is_shared_with_current_user: {
      type: "boolean",
      title: "Is Shared With Current User",
      readOnly: true,
    },
    is_read_only_by_current_user: {
      type: "boolean",
      title: "Is Read Only By Current User",
      description: "Whether current user can only read this collection",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "entity_type",
    "owner",
    "is_shared_with_current_user",
    "is_read_only_by_current_user",
  ],
  title: "CollectionWithDetailsResponse",
} as const;

export const CreateAnnotationRequestSchema = {
  properties: {
    page: {
      type: "integer",
      title: "Page",
    },
    body: {
      type: "string",
      title: "Body",
    },
    color: {
      type: "string",
      title: "Color",
    },
    excerpt: {
      type: "string",
      title: "Excerpt",
    },
    rects: {
      items: {
        $ref: "#/components/schemas/NormalizedRect",
      },
      type: "array",
      title: "Rects",
    },
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Label",
      description: "User-set identifier, used to cross-reference.",
    },
  },
  type: "object",
  required: ["page", "body", "color", "excerpt", "rects"],
  title: "CreateAnnotationRequest",
} as const;

export const CreateCollectionRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    entity_type: {
      type: "string",
      enum: ["folder", "group"],
      title: "Entity Type",
    },
  },
  type: "object",
  required: ["name", "entity_type"],
  title: "CreateCollectionRequest",
} as const;

export const CredentialsResetSchema = {
  properties: {
    password: {
      type: "string",
      format: "password",
      title: "Password",
      writeOnly: true,
    },
    password_confirm: {
      type: "string",
      format: "password",
      title: "Password Confirm",
      writeOnly: true,
    },
  },
  type: "object",
  required: ["password", "password_confirm"],
  title: "CredentialsReset",
  description: "This model is used to reset (by admin) user credentials.",
} as const;

export const CredentialsUpdateSchema = {
  properties: {
    password_old: {
      type: "string",
      format: "password",
      title: "Password Old",
      writeOnly: true,
    },
    password_new: {
      type: "string",
      format: "password",
      title: "Password New",
      writeOnly: true,
    },
    password_confirm: {
      type: "string",
      format: "password",
      title: "Password Confirm",
      writeOnly: true,
    },
  },
  type: "object",
  required: ["password_old", "password_new", "password_confirm"],
  title: "CredentialsUpdate",
  description: "This model is used to change user credentials.",
} as const;

export const DetailsUpdateSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["email", "name"],
  title: "DetailsUpdate",
} as const;

export const FileResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    collection_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Collection Id",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    page_count: {
      type: "integer",
      title: "Page Count",
    },
    tags: {
      items: {
        $ref: "#/components/schemas/TagResponse",
      },
      type: "array",
      title: "Tags",
    },
    state: {
      $ref: "#/components/schemas/FileStateResponse",
    },
    tags_name_list: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags Name List",
      readOnly: true,
    },
    is_read_only_by_current_user: {
      type: "boolean",
      title: "Is Read Only By Current User",
      description: "Whether current user can only read this file",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "page_count",
    "state",
    "tags_name_list",
    "is_read_only_by_current_user",
  ],
  title: "FileResponse",
} as const;

export const FileSearchResponseSchema = {
  properties: {
    file: {
      $ref: "#/components/schemas/FileResponse",
    },
    hits: {
      items: {
        $ref: "#/components/schemas/SearchHitResponse",
      },
      type: "array",
      title: "Hits",
    },
    score: {
      type: "string",
      enum: ["weak", "good", "strong"],
      title: "Score",
      readOnly: true,
    },
  },
  type: "object",
  required: ["file", "hits", "score"],
  title: "FileSearchResponse",
} as const;

export const FileStateResponseSchema = {
  properties: {
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
    },
    current_page: {
      type: "integer",
      title: "Current Page",
    },
    scale: {
      type: "string",
      title: "Scale",
    },
    last_read_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Last Read At",
    },
  },
  type: "object",
  required: ["is_favorite", "current_page", "scale"],
  title: "FileStateResponse",
} as const;

export const FragmentTypeSchema = {
  type: "string",
  enum: ["title", "description", "page", "annotation", "label"],
  title: "FragmentType",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const InviteToCollectionRequestSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    permission: {
      type: "string",
      enum: ["read", "modify"],
      title: "Permission",
    },
  },
  type: "object",
  required: ["email", "permission"],
  title: "InviteToCollectionRequest",
} as const;

export const LibraryTreeNodeSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    children: {
      items: {
        $ref: "#/components/schemas/LibraryTreeNode",
      },
      type: "array",
      title: "Children",
    },
    entity_type: {
      type: "string",
      enum: ["group", "folder"],
      title: "Entity Type",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    is_shared: {
      type: "boolean",
      title: "Is Shared",
      readOnly: true,
    },
    is_read_only_by_current_user: {
      type: "boolean",
      title: "Is Read Only By Current User",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "entity_type",
    "is_shared",
    "is_read_only_by_current_user",
  ],
  title: "LibraryTreeNode",
} as const;

export const NormalizedRectSchema = {
  properties: {
    top: {
      type: "number",
      maximum: 1,
      minimum: 0,
      title: "Top",
    },
    left: {
      type: "number",
      maximum: 1,
      minimum: 0,
      title: "Left",
    },
    width: {
      type: "number",
      maximum: 1,
      minimum: 0,
      title: "Width",
    },
    height: {
      type: "number",
      maximum: 1,
      minimum: 0,
      title: "Height",
    },
  },
  type: "object",
  required: ["top", "left", "width", "height"],
  title: "NormalizedRect",
  description:
    "All values are fractions (0..1) of the .page element's box,\nso they survive zoom / rotate without recomputation.",
} as const;

export const OidcGroupRule_InputSchema = {
  properties: {
    group: {
      type: "string",
      title: "Group",
      description: "Name of the group as provided by the OIDC provider",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
      description: "ID of the role to assign to users in this group",
    },
  },
  type: "object",
  required: ["group", "role_id"],
  title: "OidcGroupRule",
} as const;

export const OidcGroupRule_OutputSchema = {
  properties: {
    group: {
      type: "string",
      title: "Group",
      description: "Name of the group as provided by the OIDC provider",
    },
    role_id: {
      type: "string",
      title: "Role Id",
      description: "ID of the role to assign to users in this group",
    },
  },
  type: "object",
  required: ["group", "role_id"],
  title: "OidcGroupRule",
} as const;

export const PatchAnnotationRequestSchema = {
  properties: {
    label: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Label",
      description: "User-set identifier, used to cross-reference.",
    },
    body: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Body",
    },
    color: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Color",
    },
  },
  type: "object",
  title: "PatchAnnotationRequest",
} as const;

export const PatchFileStateRequestSchema = {
  properties: {
    current_page: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Current Page",
    },
    scale: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Scale",
    },
    is_favorite: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Favorite",
    },
  },
  type: "object",
  title: "PatchFileStateRequest",
} as const;

export const ResourcePermissionResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    name: {
      type: "string",
      title: "Name",
    },
    assignments: {
      items: {
        $ref: "#/components/schemas/AssignmentResponse",
      },
      type: "array",
      title: "Assignments",
    },
  },
  type: "object",
  required: ["id", "entity_type", "name", "assignments"],
  title: "ResourcePermissionResponse",
} as const;

export const RevokeResponseSchema = {
  properties: {
    redirect_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Redirect Url",
    },
  },
  type: "object",
  title: "RevokeResponse",
} as const;

export const RoleResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      type: "string",
      title: "Description",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    scopes: {
      $ref: "#/components/schemas/Scopes",
    },
    scopes_str: {
      type: "string",
      title: "Scopes Str",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "is_protected",
    "entity_type",
    "scopes",
    "scopes_str",
  ],
  title: "RoleResponse",
} as const;

export const ScopesSchema = {
  items: {
    type: "string",
  },
  type: "array",
  title: "Scopes",
} as const;

export const SearchHitResponseSchema = {
  properties: {
    snippet: {
      type: "string",
      title: "Snippet",
    },
    page_number: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Page Number",
    },
    fragment_type: {
      $ref: "#/components/schemas/FragmentType",
    },
    rank: {
      type: "number",
      title: "Rank",
    },
    annotation: {
      anyOf: [
        {
          $ref: "#/components/schemas/AnnotationResponse",
        },
        {
          type: "null",
        },
      ],
    },
    field: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Field",
    },
  },
  type: "object",
  required: ["snippet", "fragment_type", "rank"],
  title: "SearchHitResponse",
} as const;

export const SetupUserSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["email", "name"],
  title: "SetupUser",
  description: "Create initial application user",
} as const;

export const SsoConfigResponseSchema = {
  properties: {
    url: {
      type: "string",
      title: "Url",
    },
    is_auto_login_enabled: {
      type: "boolean",
      title: "Is Auto Login Enabled",
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["url", "is_auto_login_enabled", "name"],
  title: "SsoConfigResponse",
} as const;

export const TagResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    color: {
      type: "string",
      title: "Color",
    },
  },
  type: "object",
  required: ["id", "name", "color"],
  title: "TagResponse",
} as const;

export const TagWithDetailsResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    color: {
      type: "string",
      title: "Color",
    },
    file_count: {
      type: "integer",
      title: "File Count",
    },
  },
  type: "object",
  required: ["id", "name", "color", "file_count"],
  title: "TagWithDetailsResponse",
} as const;

export const UpdateCollectionPermissionRequestSchema = {
  properties: {
    permission: {
      type: "string",
      enum: ["read", "modify"],
      title: "Permission",
    },
  },
  type: "object",
  required: ["permission"],
  title: "UpdateCollectionPermissionRequest",
} as const;

export const UpdateCollectionRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["name"],
  title: "UpdateCollectionRequest",
} as const;

export const UpdateFileRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    tags: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags",
    },
    collection_id: {
      type: "string",
      format: "uuid",
      title: "Collection Id",
    },
  },
  type: "object",
  required: ["name", "collection_id"],
  title: "UpdateFileRequest",
} as const;

export const UpdateTagRequestSchema = {
  properties: {
    color: {
      type: "string",
      title: "Color",
    },
  },
  type: "object",
  required: ["color"],
  title: "UpdateTagRequest",
} as const;

export const UserCreateRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
  },
  type: "object",
  required: ["name", "email", "is_enabled", "role_id"],
  title: "UserCreateRequest",
} as const;

export const UserResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    auth_provider_id: {
      type: "string",
      format: "uuid",
      title: "Auth Provider Id",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
    role: {
      $ref: "#/components/schemas/RoleResponse",
    },
    is_external: {
      type: "boolean",
      title: "Is External",
    },
    auth_provider: {
      $ref: "#/components/schemas/AuthProviderResponse",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "email",
    "auth_provider_id",
    "is_enabled",
    "role_id",
    "role",
    "is_external",
    "auth_provider",
  ],
  title: "UserResponse",
} as const;

export const UserSessionResponseSchema = {
  properties: {
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    user: {
      $ref: "#/components/schemas/UserResponse",
    },
    session_id: {
      type: "string",
      format: "uuid",
      title: "Session Id",
    },
  },
  type: "object",
  required: ["user_id", "user", "session_id"],
  title: "UserSessionResponse",
  description:
    "Provides relevant information about the logged-in user. Should not include authentication data.",
} as const;

export const UserSummaryResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
  },
  type: "object",
  required: ["id", "name", "email"],
  title: "UserSummaryResponse",
} as const;

export const UserUpdateRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
  },
  type: "object",
  required: ["name", "email", "is_enabled", "role_id"],
  title: "UserUpdateRequest",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const ApiKeyResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    description: {
      type: "string",
      title: "Description",
    },
    expires_at: {
      type: "string",
      format: "date-time",
      title: "Expires At",
    },
    is_revoked: {
      type: "boolean",
      title: "Is Revoked",
    },
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    scopes: {
      $ref: "#/components/schemas/Scopes",
    },
    user: {
      anyOf: [
        {
          $ref: "#/components/schemas/UserSummaryResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: [
    "id",
    "description",
    "expires_at",
    "is_revoked",
    "user_id",
    "scopes",
  ],
  title: "ApiKeyResponse",
} as const;

export const AppStateResponseWritableSchema = {
  properties: {
    is_initial_user_created: {
      type: "boolean",
      title: "Is Initial User Created",
      default: false,
    },
    sso_servers: {
      items: {
        $ref: "#/components/schemas/SsoConfigResponse",
      },
      type: "array",
      title: "Sso Servers",
    },
    auto_login_sso_server: {
      anyOf: [
        {
          $ref: "#/components/schemas/SsoConfigResponse",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  title: "AppStateResponse",
} as const;

export const AssignmentResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    user: {
      $ref: "#/components/schemas/UserSummaryResponse",
    },
    inherited_from: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Inherited From",
    },
    permission: {
      type: "string",
      enum: ["owner", "read", "modify"],
      title: "Permission",
    },
  },
  type: "object",
  required: ["id", "user", "permission"],
  title: "AssignmentResponse",
} as const;

export const AuthProviderOidcUpdateRequestWritableSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
      default: false,
    },
    client_id: {
      type: "string",
      title: "Client Id",
    },
    client_secret: {
      type: "string",
      format: "password",
      title: "Client Secret",
      writeOnly: true,
    },
    auto_discovery_url: {
      type: "string",
      maxLength: 2083,
      minLength: 1,
      format: "uri",
      title: "Auto Discovery Url",
    },
    additional_scopes: {
      type: "string",
      minLength: 0,
      title: "Additional Scopes",
      default: "",
    },
    group_claim_name: {
      type: "string",
      title: "Group Claim Name",
      default: "groups",
    },
    group_claim_rules: {
      items: {
        $ref: "#/components/schemas/OidcGroupRule-Input",
      },
      type: "array",
      title: "Group Claim Rules",
    },
    auto_login: {
      type: "boolean",
      title: "Auto Login",
      default: false,
    },
  },
  type: "object",
  required: ["name", "client_id", "client_secret", "auto_discovery_url"],
  title: "AuthProviderOidcUpdateRequest",
} as const;

export const CollectionWithDetailsResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    entity_type: {
      type: "string",
      enum: ["folder", "group"],
      title: "Entity Type",
    },
    files: {
      items: {
        $ref: "#/components/schemas/FileResponseWritable",
      },
      type: "array",
      title: "Files",
    },
    owner: {
      $ref: "#/components/schemas/UserSummaryResponse",
    },
  },
  type: "object",
  required: ["id", "name", "entity_type", "owner"],
  title: "CollectionWithDetailsResponse",
} as const;

export const FileResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    collection_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Collection Id",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    page_count: {
      type: "integer",
      title: "Page Count",
    },
    tags: {
      items: {
        $ref: "#/components/schemas/TagResponse",
      },
      type: "array",
      title: "Tags",
    },
    state: {
      $ref: "#/components/schemas/FileStateResponse",
    },
  },
  type: "object",
  required: ["id", "name", "page_count", "state"],
  title: "FileResponse",
} as const;

export const FileSearchResponseWritableSchema = {
  properties: {
    file: {
      $ref: "#/components/schemas/FileResponseWritable",
    },
    hits: {
      items: {
        $ref: "#/components/schemas/SearchHitResponse",
      },
      type: "array",
      title: "Hits",
    },
  },
  type: "object",
  required: ["file", "hits"],
  title: "FileSearchResponse",
} as const;

export const LibraryTreeNodeWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    children: {
      items: {
        $ref: "#/components/schemas/LibraryTreeNodeWritable",
      },
      type: "array",
      title: "Children",
    },
    entity_type: {
      type: "string",
      enum: ["group", "folder"],
      title: "Entity Type",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["id", "name", "entity_type"],
  title: "LibraryTreeNode",
} as const;

export const ResourcePermissionResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    name: {
      type: "string",
      title: "Name",
    },
    assignments: {
      items: {
        $ref: "#/components/schemas/AssignmentResponseWritable",
      },
      type: "array",
      title: "Assignments",
    },
  },
  type: "object",
  required: ["id", "entity_type", "name", "assignments"],
  title: "ResourcePermissionResponse",
} as const;

export const RoleResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      type: "string",
      title: "Description",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    scopes: {
      $ref: "#/components/schemas/Scopes",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "is_protected",
    "entity_type",
    "scopes",
  ],
  title: "RoleResponse",
} as const;

export const SetupUserWritableSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
      writeOnly: true,
    },
    password_confirm: {
      type: "string",
      format: "password",
      title: "Password Confirm",
      writeOnly: true,
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["email", "password", "password_confirm", "name"],
  title: "SetupUser",
  description: "Create initial application user",
} as const;

export const UserCreateRequestWritableSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
      writeOnly: true,
    },
    password_confirm: {
      type: "string",
      format: "password",
      title: "Password Confirm",
      writeOnly: true,
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
  },
  type: "object",
  required: [
    "name",
    "email",
    "password",
    "password_confirm",
    "is_enabled",
    "role_id",
  ],
  title: "UserCreateRequest",
} as const;

export const UserResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    auth_provider_id: {
      type: "string",
      format: "uuid",
      title: "Auth Provider Id",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
    role: {
      $ref: "#/components/schemas/RoleResponseWritable",
    },
    is_external: {
      type: "boolean",
      title: "Is External",
    },
    auth_provider: {
      $ref: "#/components/schemas/AuthProviderResponse",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "email",
    "auth_provider_id",
    "is_enabled",
    "role_id",
    "role",
    "is_external",
    "auth_provider",
  ],
  title: "UserResponse",
} as const;

export const UserSessionResponseWritableSchema = {
  properties: {
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    user: {
      $ref: "#/components/schemas/UserResponseWritable",
    },
    session_id: {
      type: "string",
      format: "uuid",
      title: "Session Id",
    },
  },
  type: "object",
  required: ["user_id", "user", "session_id"],
  title: "UserSessionResponse",
  description:
    "Provides relevant information about the logged-in user. Should not include authentication data.",
} as const;
