// This file is auto-generated by @hey-api/openapi-ts

export const AccessTokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
    },
    expires: {
      type: "string",
      format: "date-time",
      title: "Expires",
    },
  },
  type: "object",
  required: ["access_token", "token_type", "expires"],
  title: "AccessToken",
  description: "API access token.",
} as const;

export const AppStateResponseSchema = {
  properties: {
    is_initial_user_created: {
      type: "boolean",
      title: "Is Initial User Created",
      default: false,
    },
    is_setup_complete: {
      type: "boolean",
      title: "Is Setup Complete",
      description: "Check if the setup is complete",
      readOnly: true,
    },
  },
  type: "object",
  required: ["is_setup_complete"],
  title: "AppStateResponse",
} as const;

export const AuthProviderResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
  },
  type: "object",
  required: ["id", "name", "entity_type", "is_enabled", "is_protected"],
  title: "AuthProviderResponse",
} as const;

export const Body_CreateAuthTokenSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: "string",
          pattern: "^password$",
        },
        {
          type: "null",
        },
      ],
      title: "Grant Type",
    },
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
    },
    scope: {
      type: "string",
      title: "Scope",
      default: "",
    },
    client_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Id",
    },
    client_secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      format: "password",
      title: "Client Secret",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "Body_CreateAuthToken",
} as const;

export const Body_UploadFileSchema = {
  properties: {
    file: {
      type: "string",
      contentMediaType: "application/octet-stream",
      title: "File",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    folder_id: {
      type: "string",
      format: "uuid",
      title: "Folder Id",
    },
    tags: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags",
    },
  },
  type: "object",
  required: ["file", "name", "folder_id"],
  title: "Body_UploadFile",
} as const;

export const CollectionResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "CollectionResponse",
} as const;

export const CreateCollectionRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["name"],
  title: "CreateCollectionRequest",
} as const;

export const CreateFolderRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["name"],
  title: "CreateFolderRequest",
} as const;

export const CredentialsUpdateSchema = {
  properties: {
    password_old: {
      type: "string",
      format: "password",
      title: "Password Old",
      writeOnly: true,
    },
    password_new: {
      type: "string",
      format: "password",
      title: "Password New",
      writeOnly: true,
    },
    password_confirm: {
      type: "string",
      format: "password",
      title: "Password Confirm",
      writeOnly: true,
    },
  },
  type: "object",
  required: ["password_old", "password_new", "password_confirm"],
  title: "CredentialsUpdate",
  description: "This model is used to change user credentials.",
} as const;

export const DetailsUpdateSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["email", "name"],
  title: "DetailsUpdate",
} as const;

export const FileResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    folder_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Folder Id",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    tags: {
      items: {
        $ref: "#/components/schemas/TagResponse",
      },
      type: "array",
      title: "Tags",
    },
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
    },
    page_count: {
      type: "integer",
      title: "Page Count",
    },
    current_page: {
      type: "integer",
      title: "Current Page",
    },
    scale: {
      type: "string",
      title: "Scale",
    },
    tags_name_list: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags Name List",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "is_favorite",
    "page_count",
    "current_page",
    "scale",
    "tags_name_list",
  ],
  title: "FileResponse",
} as const;

export const FolderResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    files: {
      items: {
        $ref: "#/components/schemas/FileResponse",
      },
      type: "array",
      title: "Files",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "FolderResponse",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const LibraryTreeNodeSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    children: {
      items: {
        $ref: "#/components/schemas/LibraryTreeNode",
      },
      type: "array",
      title: "Children",
    },
    entity_type: {
      type: "string",
      enum: ["collection", "folder"],
      title: "Entity Type",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["id", "name", "entity_type"],
  title: "LibraryTreeNode",
} as const;

export const PatchFileStateRequestSchema = {
  properties: {
    current_page: {
      anyOf: [
        {
          type: "integer",
          minimum: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Current Page",
    },
    scale: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Scale",
    },
  },
  type: "object",
  title: "PatchFileStateRequest",
} as const;

export const RoleResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      type: "string",
      title: "Description",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    scopes: {
      type: "string",
      title: "Scopes",
    },
    scope_list: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Scope List",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "is_protected",
    "entity_type",
    "scopes",
    "scope_list",
  ],
  title: "RoleResponse",
} as const;

export const SetupUserSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["email", "name"],
  title: "SetupUser",
  description: "Create initial application user",
} as const;

export const TagDetailResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    color: {
      type: "string",
      title: "Color",
    },
    file_count: {
      type: "integer",
      title: "File Count",
    },
  },
  type: "object",
  required: ["id", "name", "color", "file_count"],
  title: "TagDetailResponse",
} as const;

export const TagResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    color: {
      type: "string",
      title: "Color",
    },
  },
  type: "object",
  required: ["id", "name", "color"],
  title: "TagResponse",
} as const;

export const UpdateCollectionRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["name"],
  title: "UpdateCollectionRequest",
} as const;

export const UpdateFileRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    tags: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tags",
    },
    folder_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Folder Id",
    },
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
      default: false,
    },
  },
  type: "object",
  required: ["name"],
  title: "UpdateFileRequest",
} as const;

export const UpdateFolderRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
  },
  type: "object",
  required: ["name"],
  title: "UpdateFolderRequest",
} as const;

export const UpdateTagRequestSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    color: {
      type: "string",
      title: "Color",
    },
  },
  type: "object",
  required: ["name", "color"],
  title: "UpdateTagRequest",
} as const;

export const UserResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    auth_provider_id: {
      type: "string",
      format: "uuid",
      title: "Auth Provider Id",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
    role: {
      $ref: "#/components/schemas/RoleResponse",
    },
    auth_provider: {
      $ref: "#/components/schemas/AuthProviderResponse",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "email",
    "auth_provider_id",
    "is_enabled",
    "role_id",
    "role",
    "auth_provider",
  ],
  title: "UserResponse",
} as const;

export const UserSessionResponseSchema = {
  properties: {
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    user: {
      $ref: "#/components/schemas/UserResponse",
    },
    session_id: {
      type: "string",
      format: "uuid",
      title: "Session Id",
    },
  },
  type: "object",
  required: ["user_id", "user", "session_id"],
  title: "UserSessionResponse",
  description:
    "Provides relevant information about the logged-in user. Should not include authentication data.",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const AppStateResponseWritableSchema = {
  properties: {
    is_initial_user_created: {
      type: "boolean",
      title: "Is Initial User Created",
      default: false,
    },
  },
  type: "object",
  title: "AppStateResponse",
} as const;

export const FileResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    folder_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Folder Id",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    tags: {
      items: {
        $ref: "#/components/schemas/TagResponse",
      },
      type: "array",
      title: "Tags",
    },
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
    },
    page_count: {
      type: "integer",
      title: "Page Count",
    },
    current_page: {
      type: "integer",
      title: "Current Page",
    },
    scale: {
      type: "string",
      title: "Scale",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "is_favorite",
    "page_count",
    "current_page",
    "scale",
  ],
  title: "FileResponse",
} as const;

export const FolderResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    parent_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Id",
    },
    files: {
      items: {
        $ref: "#/components/schemas/FileResponseWritable",
      },
      type: "array",
      title: "Files",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "FolderResponse",
} as const;

export const RoleResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      type: "string",
      title: "Description",
    },
    is_protected: {
      type: "boolean",
      title: "Is Protected",
    },
    entity_type: {
      type: "string",
      title: "Entity Type",
    },
    scopes: {
      type: "string",
      title: "Scopes",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "is_protected",
    "entity_type",
    "scopes",
  ],
  title: "RoleResponse",
} as const;

export const SetupUserWritableSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
      writeOnly: true,
    },
    password_confirm: {
      type: "string",
      format: "password",
      title: "Password Confirm",
      writeOnly: true,
    },
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["email", "password", "password_confirm", "name"],
  title: "SetupUser",
  description: "Create initial application user",
} as const;

export const UserResponseWritableSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    auth_provider_id: {
      type: "string",
      format: "uuid",
      title: "Auth Provider Id",
    },
    is_enabled: {
      type: "boolean",
      title: "Is Enabled",
    },
    role_id: {
      type: "string",
      format: "uuid",
      title: "Role Id",
    },
    role: {
      $ref: "#/components/schemas/RoleResponseWritable",
    },
    auth_provider: {
      $ref: "#/components/schemas/AuthProviderResponse",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "email",
    "auth_provider_id",
    "is_enabled",
    "role_id",
    "role",
    "auth_provider",
  ],
  title: "UserResponse",
} as const;

export const UserSessionResponseWritableSchema = {
  properties: {
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
    },
    user: {
      $ref: "#/components/schemas/UserResponseWritable",
    },
    session_id: {
      type: "string",
      format: "uuid",
      title: "Session Id",
    },
  },
  type: "object",
  required: ["user_id", "user", "session_id"],
  title: "UserSessionResponse",
  description:
    "Provides relevant information about the logged-in user. Should not include authentication data.",
} as const;
