// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import {
  createApiKeyResponseTransformer,
  createAuthTokenResponseTransformer,
  createPersonalApiKeyResponseTransformer,
  getCollectionFilesResponseTransformer,
  getFileDetailsResponseTransformer,
  getFileStateResponseTransformer,
  getLibraryTreeResponseTransformer,
  listActiveTasksResponseTransformer,
  listAnnotationsResponseTransformer,
  listApiKeysResponseTransformer,
  listFilesResponseTransformer,
  listPersonalApiKeysResponseTransformer,
  listTaskHistoryResponseTransformer,
  refreshAuthTokenResponseTransformer,
  resetApiKeyResponseTransformer,
  resetPersonalApiKeyResponseTransformer,
  searchFilesResponseTransformer,
} from "./transformers.gen";
import type {
  CreateAnnotationData,
  CreateAnnotationErrors,
  CreateAnnotationResponses,
  CreateApiKeyData,
  CreateApiKeyErrors,
  CreateApiKeyResponses,
  CreateAuthTokenData,
  CreateAuthTokenErrors,
  CreateAuthTokenResponses,
  CreateCollectionData,
  CreateCollectionErrors,
  CreateCollectionResponses,
  CreateOidcAuthProviderData,
  CreateOidcAuthProviderErrors,
  CreateOidcAuthProviderResponses,
  CreatePersonalApiKeyData,
  CreatePersonalApiKeyErrors,
  CreatePersonalApiKeyResponses,
  CreateSetupUserData,
  CreateSetupUserErrors,
  CreateSetupUserResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteAnnotationData,
  DeleteAnnotationErrors,
  DeleteAnnotationResponses,
  DeleteCollectionData,
  DeleteCollectionErrors,
  DeleteCollectionPermissionData,
  DeleteCollectionPermissionErrors,
  DeleteCollectionPermissionResponses,
  DeleteCollectionResponses,
  DeleteFileData,
  DeleteFileErrors,
  DeleteFileResponses,
  DeleteOidcAuthProviderData,
  DeleteOidcAuthProviderErrors,
  DeleteOidcAuthProviderResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  GetApiDocsData,
  GetApiDocsResponses,
  GetAppStateData,
  GetAppStateResponses,
  GetAppStatusData,
  GetAppStatusResponses,
  GetCollectionData,
  GetCollectionErrors,
  GetCollectionFilesData,
  GetCollectionFilesErrors,
  GetCollectionFilesResponses,
  GetCollectionPermissionsData,
  GetCollectionPermissionsErrors,
  GetCollectionPermissionsResponses,
  GetCollectionResponses,
  GetCurrentSessionData,
  GetCurrentSessionResponses,
  GetFileData,
  GetFileDetailsData,
  GetFileDetailsErrors,
  GetFileDetailsResponses,
  GetFileErrors,
  GetFileResponses,
  GetFileStateData,
  GetFileStateErrors,
  GetFileStateResponses,
  GetFileThumbnailData,
  GetFileThumbnailErrors,
  GetFileThumbnailResponses,
  GetLibraryTreeData,
  GetLibraryTreeResponses,
  GetOidcAuthProviderData,
  GetOidcAuthProviderErrors,
  GetOidcAuthProviderResponses,
  GetOpdsFileData,
  GetOpdsFileErrors,
  GetOpdsFileResponses,
  GetOpdsFileThumbnailData,
  GetOpdsFileThumbnailErrors,
  GetOpdsFileThumbnailResponses,
  InviteToCollectionData,
  InviteToCollectionErrors,
  InviteToCollectionResponses,
  ListActiveTasksData,
  ListActiveTasksResponses,
  ListAnnotationLabelsData,
  ListAnnotationLabelsResponses,
  ListAnnotationsData,
  ListAnnotationsErrors,
  ListAnnotationsResponses,
  ListApiKeysData,
  ListApiKeysResponses,
  ListAuthorsData,
  ListAuthorsResponses,
  ListAuthProvidersData,
  ListAuthProvidersResponses,
  ListCollectionMoveTargetsData,
  ListCollectionMoveTargetsErrors,
  ListCollectionMoveTargetsResponses,
  ListCollectionsData,
  ListCollectionsResponses,
  ListFileMoveTargetsData,
  ListFileMoveTargetsErrors,
  ListFileMoveTargetsResponses,
  ListFilesData,
  ListFilesErrors,
  ListFilesResponses,
  ListOidcAuthProvidersData,
  ListOidcAuthProvidersResponses,
  ListPersonalApiKeysData,
  ListPersonalApiKeysResponses,
  ListRolesData,
  ListRolesResponses,
  ListTagsData,
  ListTagsResponses,
  ListTaskHistoryData,
  ListTaskHistoryErrors,
  ListTaskHistoryResponses,
  ListUsersData,
  ListUsersResponses,
  OidcCallbackData,
  OidcCallbackErrors,
  OidcLoginData,
  OidcLoginErrors,
  OidcLoginResponses,
  OpdsAllData,
  OpdsAllResponses,
  OpdsCollectionData,
  OpdsCollectionErrors,
  OpdsCollectionResponses,
  OpdsCollectionsData,
  OpdsCollectionsResponses,
  OpdsOpenSearchData,
  OpdsOpenSearchResponses,
  OpdsRootData,
  OpdsRootResponses,
  OpdsSearchData,
  OpdsSearchErrors,
  OpdsSearchResponses,
  OpdsShelfData,
  OpdsShelfResponses,
  PatchAnnotationData,
  PatchAnnotationErrors,
  PatchAnnotationResponses,
  PatchFileStateData,
  PatchFileStateErrors,
  PatchFileStateResponses,
  RefreshAuthTokenData,
  RefreshAuthTokenResponses,
  ResetApiKeyData,
  ResetApiKeyErrors,
  ResetApiKeyResponses,
  ResetPersonalApiKeyData,
  ResetPersonalApiKeyErrors,
  ResetPersonalApiKeyResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  RevokeApiKeyData,
  RevokeApiKeyErrors,
  RevokeApiKeyResponses,
  RevokePersonalApiKeyData,
  RevokePersonalApiKeyErrors,
  RevokePersonalApiKeyResponses,
  RevokeTokenData,
  RevokeTokenResponses,
  SearchFilesData,
  SearchFilesErrors,
  SearchFilesResponses,
  UpdateCollectionData,
  UpdateCollectionErrors,
  UpdateCollectionPermissionData,
  UpdateCollectionPermissionErrors,
  UpdateCollectionPermissionResponses,
  UpdateCollectionResponses,
  UpdateFileData,
  UpdateFileErrors,
  UpdateFileResponses,
  UpdateOidcAuthProviderData,
  UpdateOidcAuthProviderErrors,
  UpdateOidcAuthProviderResponses,
  UpdateTagData,
  UpdateTagErrors,
  UpdateTagResponses,
  UpdateUserAccountDetailsData,
  UpdateUserAccountDetailsErrors,
  UpdateUserAccountDetailsResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserPasswordData,
  UpdateUserPasswordErrors,
  UpdateUserPasswordResponses,
  UpdateUserResponses,
  UploadFileData,
  UploadFileErrors,
  UploadFileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Current Session
 *
 * Get information about the current user session.
 */
export const getCurrentSession = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentSessionData, ThrowOnError>,
): RequestResult<GetCurrentSessionResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetCurrentSessionResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/session",
    ...options,
  });

/**
 * Revoke Token
 *
 * Invalidate the access and refresh tokens
 */
export const revokeToken = <ThrowOnError extends boolean = false>(
  options?: Options<RevokeTokenData, ThrowOnError>,
): RequestResult<RevokeTokenResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).delete<
    RevokeTokenResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        key: "RefreshManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/token",
    ...options,
  });

/**
 * Authenticate With Password
 *
 * Create access and refresh tokens using Basic Auth.
 */
export const createAuthToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateAuthTokenData, ThrowOnError>,
): RequestResult<
  CreateAuthTokenResponses,
  CreateAuthTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateAuthTokenResponses,
    CreateAuthTokenErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseTransformer: createAuthTokenResponseTransformer,
    url: "/api/v1/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Refresh Token
 *
 * Receive a new access token using the refresh token.
 */
export const refreshAuthToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshAuthTokenData, ThrowOnError>,
): RequestResult<RefreshAuthTokenResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    RefreshAuthTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: refreshAuthTokenResponseTransformer,
    security: [
      {
        key: "RefreshManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/refresh",
    ...options,
  });

/**
 * Oidc Authorize
 */
export const oidcLogin = <ThrowOnError extends boolean = false>(
  options: Options<OidcLoginData, ThrowOnError>,
): RequestResult<OidcLoginResponses, OidcLoginErrors, ThrowOnError> =>
  (options.client ?? client).get<
    OidcLoginResponses,
    OidcLoginErrors,
    ThrowOnError
  >({ url: "/api/v1/auth/oidc/{id}", ...options });

/**
 * Oidc Callback
 */
export const oidcCallback = <ThrowOnError extends boolean = false>(
  options: Options<OidcCallbackData, ThrowOnError>,
): RequestResult<unknown, OidcCallbackErrors, ThrowOnError> =>
  (options.client ?? client).get<unknown, OidcCallbackErrors, ThrowOnError>({
    url: "/api/v1/auth/oidc/{id}/callback",
    ...options,
  });

/**
 * List Collections
 */
export const listCollections = <ThrowOnError extends boolean = false>(
  options?: Options<ListCollectionsData, ThrowOnError>,
): RequestResult<ListCollectionsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListCollectionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections",
    ...options,
  });

/**
 * Create Collection
 */
export const createCollection = <ThrowOnError extends boolean = false>(
  options: Options<CreateCollectionData, ThrowOnError>,
): RequestResult<
  CreateCollectionResponses,
  CreateCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCollectionResponses,
    CreateCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Collection Move Targets
 */
export const listCollectionMoveTargets = <ThrowOnError extends boolean = false>(
  options: Options<ListCollectionMoveTargetsData, ThrowOnError>,
): RequestResult<
  ListCollectionMoveTargetsResponses,
  ListCollectionMoveTargetsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListCollectionMoveTargetsResponses,
    ListCollectionMoveTargetsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}/move-targets",
    ...options,
  });

/**
 * Delete Collection
 */
export const deleteCollection = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCollectionData, ThrowOnError>,
): RequestResult<
  DeleteCollectionResponses,
  DeleteCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCollectionResponses,
    DeleteCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}",
    ...options,
  });

/**
 * Get Collection
 */
export const getCollection = <ThrowOnError extends boolean = false>(
  options: Options<GetCollectionData, ThrowOnError>,
): RequestResult<GetCollectionResponses, GetCollectionErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetCollectionResponses,
    GetCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}",
    ...options,
  });

/**
 * Update Collection
 */
export const updateCollection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCollectionData, ThrowOnError>,
): RequestResult<
  UpdateCollectionResponses,
  UpdateCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCollectionResponses,
    UpdateCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Collection Files
 */
export const getCollectionFiles = <ThrowOnError extends boolean = false>(
  options: Options<GetCollectionFilesData, ThrowOnError>,
): RequestResult<
  GetCollectionFilesResponses,
  GetCollectionFilesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCollectionFilesResponses,
    GetCollectionFilesErrors,
    ThrowOnError
  >({
    responseTransformer: getCollectionFilesResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}/files",
    ...options,
  });

/**
 * Get Collection Permissions
 */
export const getCollectionPermissions = <ThrowOnError extends boolean = false>(
  options: Options<GetCollectionPermissionsData, ThrowOnError>,
): RequestResult<
  GetCollectionPermissionsResponses,
  GetCollectionPermissionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCollectionPermissionsResponses,
    GetCollectionPermissionsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}/permissions",
    ...options,
  });

/**
 * Invite To Collection
 */
export const inviteToCollection = <ThrowOnError extends boolean = false>(
  options: Options<InviteToCollectionData, ThrowOnError>,
): RequestResult<
  InviteToCollectionResponses,
  InviteToCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    InviteToCollectionResponses,
    InviteToCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{id}/permissions/invite",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Collection Permission
 */
export const deleteCollectionPermission = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCollectionPermissionData, ThrowOnError>,
): RequestResult<
  DeleteCollectionPermissionResponses,
  DeleteCollectionPermissionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCollectionPermissionResponses,
    DeleteCollectionPermissionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{collection_id}/permissions/{id}",
    ...options,
  });

/**
 * Update Collection Permission
 */
export const updateCollectionPermission = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCollectionPermissionData, ThrowOnError>,
): RequestResult<
  UpdateCollectionPermissionResponses,
  UpdateCollectionPermissionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCollectionPermissionResponses,
    UpdateCollectionPermissionErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/collections/{collection_id}/permissions/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List File Move Targets
 */
export const listFileMoveTargets = <ThrowOnError extends boolean = false>(
  options: Options<ListFileMoveTargetsData, ThrowOnError>,
): RequestResult<
  ListFileMoveTargetsResponses,
  ListFileMoveTargetsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListFileMoveTargetsResponses,
    ListFileMoveTargetsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}/move-targets",
    ...options,
  });

/**
 * Delete File
 */
export const deleteFile = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFileData, ThrowOnError>,
): RequestResult<DeleteFileResponses, DeleteFileErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteFileResponses,
    DeleteFileErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}",
    ...options,
  });

/**
 * Get File Details
 */
export const getFileDetails = <ThrowOnError extends boolean = false>(
  options: Options<GetFileDetailsData, ThrowOnError>,
): RequestResult<GetFileDetailsResponses, GetFileDetailsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFileDetailsResponses,
    GetFileDetailsErrors,
    ThrowOnError
  >({
    responseTransformer: getFileDetailsResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}",
    ...options,
  });

/**
 * Update File
 */
export const updateFile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFileData, ThrowOnError>,
): RequestResult<UpdateFileResponses, UpdateFileErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateFileResponses,
    UpdateFileErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get File State
 */
export const getFileState = <ThrowOnError extends boolean = false>(
  options: Options<GetFileStateData, ThrowOnError>,
): RequestResult<GetFileStateResponses, GetFileStateErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetFileStateResponses,
    GetFileStateErrors,
    ThrowOnError
  >({
    responseTransformer: getFileStateResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}/state",
    ...options,
  });

/**
 * Patch File State
 */
export const patchFileState = <ThrowOnError extends boolean = false>(
  options: Options<PatchFileStateData, ThrowOnError>,
): RequestResult<PatchFileStateResponses, PatchFileStateErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    PatchFileStateResponses,
    PatchFileStateErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}/state",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Library Tree
 */
export const getLibraryTree = <ThrowOnError extends boolean = false>(
  options?: Options<GetLibraryTreeData, ThrowOnError>,
): RequestResult<GetLibraryTreeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetLibraryTreeResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getLibraryTreeResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/tree",
    ...options,
  });

/**
 * List Files
 */
export const listFiles = <ThrowOnError extends boolean = false>(
  options?: Options<ListFilesData, ThrowOnError>,
): RequestResult<ListFilesResponses, ListFilesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListFilesResponses,
    ListFilesErrors,
    ThrowOnError
  >({
    responseTransformer: listFilesResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files",
    ...options,
  });

/**
 * Upload File
 */
export const uploadFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadFileData, ThrowOnError>,
): RequestResult<UploadFileResponses, UploadFileErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadFileResponses,
    UploadFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Download File
 */
export const getFile = <ThrowOnError extends boolean = false>(
  options: Options<GetFileData, ThrowOnError>,
): RequestResult<GetFileResponses, GetFileErrors, ThrowOnError> =>
  (options.client ?? client).get<GetFileResponses, GetFileErrors, ThrowOnError>(
    {
      security: [
        {
          key: "AccessManagerDependency",
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/api/v1/library/files/{id}/download",
      ...options,
    },
  );

/**
 * List Annotation Labels
 */
export const listAnnotationLabels = <ThrowOnError extends boolean = false>(
  options?: Options<ListAnnotationLabelsData, ThrowOnError>,
): RequestResult<ListAnnotationLabelsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListAnnotationLabelsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/annotations/labels",
    ...options,
  });

/**
 * List Annotations
 */
export const listAnnotations = <ThrowOnError extends boolean = false>(
  options: Options<ListAnnotationsData, ThrowOnError>,
): RequestResult<
  ListAnnotationsResponses,
  ListAnnotationsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListAnnotationsResponses,
    ListAnnotationsErrors,
    ThrowOnError
  >({
    responseTransformer: listAnnotationsResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}/annotations",
    ...options,
  });

/**
 * Create Annotation
 */
export const createAnnotation = <ThrowOnError extends boolean = false>(
  options: Options<CreateAnnotationData, ThrowOnError>,
): RequestResult<
  CreateAnnotationResponses,
  CreateAnnotationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateAnnotationResponses,
    CreateAnnotationErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}/annotations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete  Annotation
 */
export const deleteAnnotation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAnnotationData, ThrowOnError>,
): RequestResult<
  DeleteAnnotationResponses,
  DeleteAnnotationErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteAnnotationResponses,
    DeleteAnnotationErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{file_id}/annotations/{id}",
    ...options,
  });

/**
 * Patch Annotation
 */
export const patchAnnotation = <ThrowOnError extends boolean = false>(
  options: Options<PatchAnnotationData, ThrowOnError>,
): RequestResult<
  PatchAnnotationResponses,
  PatchAnnotationErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchAnnotationResponses,
    PatchAnnotationErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{file_id}/annotations/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get File Thumbnail
 */
export const getFileThumbnail = <ThrowOnError extends boolean = false>(
  options: Options<GetFileThumbnailData, ThrowOnError>,
): RequestResult<
  GetFileThumbnailResponses,
  GetFileThumbnailErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFileThumbnailResponses,
    GetFileThumbnailErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/files/{id}/thumbnail",
    ...options,
  });

/**
 * List Tags
 */
export const listTags = <ThrowOnError extends boolean = false>(
  options?: Options<ListTagsData, ThrowOnError>,
): RequestResult<ListTagsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListTagsResponses, unknown, ThrowOnError>({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/tags",
    ...options,
  });

/**
 * Update Tag
 */
export const updateTag = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTagData, ThrowOnError>,
): RequestResult<UpdateTagResponses, UpdateTagErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateTagResponses,
    UpdateTagErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/tags/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Authors
 */
export const listAuthors = <ThrowOnError extends boolean = false>(
  options?: Options<ListAuthorsData, ThrowOnError>,
): RequestResult<ListAuthorsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListAuthorsResponses, unknown, ThrowOnError>({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/library/authors",
    ...options,
  });

/**
 * Search Files
 */
export const searchFiles = <ThrowOnError extends boolean = false>(
  options?: Options<SearchFilesData, ThrowOnError>,
): RequestResult<SearchFilesResponses, SearchFilesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    SearchFilesResponses,
    SearchFilesErrors,
    ThrowOnError
  >({
    responseTransformer: searchFilesResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/search/files",
    ...options,
  });

/**
 * State
 *
 * Get current app state
 */
export const getAppState = <ThrowOnError extends boolean = false>(
  options?: Options<GetAppStateData, ThrowOnError>,
): RequestResult<GetAppStateResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetAppStateResponses, unknown, ThrowOnError>({
    url: "/api/v1/setup/state",
    ...options,
  });

/**
 * Setup User
 *
 * Create initial app admin user
 */
export const createSetupUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateSetupUserData, ThrowOnError>,
): RequestResult<
  CreateSetupUserResponses,
  CreateSetupUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSetupUserResponses,
    CreateSetupUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/setup/user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Status
 *
 * liveness / readiness probe
 */
export const getAppStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetAppStatusData, ThrowOnError>,
): RequestResult<GetAppStatusResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetAppStatusResponses, unknown, ThrowOnError>(
    { url: "/api/v1/setup/status", ...options },
  );

/**
 * Update Details
 *
 * Update current user's details.
 */
export const updateUserAccountDetails = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserAccountDetailsData, ThrowOnError>,
): RequestResult<
  UpdateUserAccountDetailsResponses,
  UpdateUserAccountDetailsErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateUserAccountDetailsResponses,
    UpdateUserAccountDetailsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/account/details",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Password
 *
 * Update current user's password.
 */
export const updateUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserPasswordData, ThrowOnError>,
): RequestResult<
  UpdateUserPasswordResponses,
  UpdateUserPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateUserPasswordResponses,
    UpdateUserPasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/account/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Api Keys
 */
export const listPersonalApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<ListPersonalApiKeysData, ThrowOnError>,
): RequestResult<ListPersonalApiKeysResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListPersonalApiKeysResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listPersonalApiKeysResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/account/keys",
    ...options,
  });

/**
 * Create Api Key
 */
export const createPersonalApiKey = <ThrowOnError extends boolean = false>(
  options: Options<CreatePersonalApiKeyData, ThrowOnError>,
): RequestResult<
  CreatePersonalApiKeyResponses,
  CreatePersonalApiKeyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreatePersonalApiKeyResponses,
    CreatePersonalApiKeyErrors,
    ThrowOnError
  >({
    responseTransformer: createPersonalApiKeyResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/account/keys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke Api Key
 */
export const revokePersonalApiKey = <ThrowOnError extends boolean = false>(
  options: Options<RevokePersonalApiKeyData, ThrowOnError>,
): RequestResult<
  RevokePersonalApiKeyResponses,
  RevokePersonalApiKeyErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RevokePersonalApiKeyResponses,
    RevokePersonalApiKeyErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/account/keys/{id}",
    ...options,
  });

/**
 * Reset Api Key
 */
export const resetPersonalApiKey = <ThrowOnError extends boolean = false>(
  options: Options<ResetPersonalApiKeyData, ThrowOnError>,
): RequestResult<
  ResetPersonalApiKeyResponses,
  ResetPersonalApiKeyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetPersonalApiKeyResponses,
    ResetPersonalApiKeyErrors,
    ThrowOnError
  >({
    responseTransformer: resetPersonalApiKeyResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/account/keys/{id}/reset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Roles
 */
export const listRoles = <ThrowOnError extends boolean = false>(
  options?: Options<ListRolesData, ThrowOnError>,
): RequestResult<ListRolesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListRolesResponses, unknown, ThrowOnError>({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/roles",
    ...options,
  });

/**
 * List Users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>,
): RequestResult<ListUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/users",
    ...options,
  });

/**
 * Create User
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/users/{id}",
    ...options,
  });

/**
 * Update User
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset User Password
 */
export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>,
): RequestResult<
  ResetUserPasswordResponses,
  ResetUserPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/users/{id}/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Providers
 */
export const listAuthProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ListAuthProvidersData, ThrowOnError>,
): RequestResult<ListAuthProvidersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListAuthProvidersResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/auth_providers",
    ...options,
  });

/**
 * List Oidc Providers
 */
export const listOidcAuthProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ListOidcAuthProvidersData, ThrowOnError>,
): RequestResult<ListOidcAuthProvidersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListOidcAuthProvidersResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/auth_providers/oidc",
    ...options,
  });

/**
 * Create Provider Oidc
 */
export const createOidcAuthProvider = <ThrowOnError extends boolean = false>(
  options: Options<CreateOidcAuthProviderData, ThrowOnError>,
): RequestResult<
  CreateOidcAuthProviderResponses,
  CreateOidcAuthProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOidcAuthProviderResponses,
    CreateOidcAuthProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/auth_providers/oidc",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Oidc Provider
 */
export const deleteOidcAuthProvider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteOidcAuthProviderData, ThrowOnError>,
): RequestResult<
  DeleteOidcAuthProviderResponses,
  DeleteOidcAuthProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteOidcAuthProviderResponses,
    DeleteOidcAuthProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/auth_providers/oidc/{id}",
    ...options,
  });

/**
 * Get Oidc Provider
 */
export const getOidcAuthProvider = <ThrowOnError extends boolean = false>(
  options: Options<GetOidcAuthProviderData, ThrowOnError>,
): RequestResult<
  GetOidcAuthProviderResponses,
  GetOidcAuthProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOidcAuthProviderResponses,
    GetOidcAuthProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/auth_providers/oidc/{id}",
    ...options,
  });

/**
 * Update Provider Oidc
 */
export const updateOidcAuthProvider = <ThrowOnError extends boolean = false>(
  options: Options<UpdateOidcAuthProviderData, ThrowOnError>,
): RequestResult<
  UpdateOidcAuthProviderResponses,
  UpdateOidcAuthProviderErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateOidcAuthProviderResponses,
    UpdateOidcAuthProviderErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/identity/auth_providers/oidc/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Api Docs
 *
 * Get API documentation in OpenAPI format.
 */
export const getApiDocs = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiDocsData, ThrowOnError>,
): RequestResult<GetApiDocsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiDocsResponses, unknown, ThrowOnError>({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/api/docs",
    ...options,
  });

/**
 * List Api Keys
 */
export const listApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<ListApiKeysData, ThrowOnError>,
): RequestResult<ListApiKeysResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListApiKeysResponses, unknown, ThrowOnError>({
    responseTransformer: listApiKeysResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/api/keys",
    ...options,
  });

/**
 * Create Api Key
 */
export const createApiKey = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiKeyData, ThrowOnError>,
): RequestResult<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateApiKeyResponses,
    CreateApiKeyErrors,
    ThrowOnError
  >({
    responseTransformer: createApiKeyResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/api/keys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke Api Key
 */
export const revokeApiKey = <ThrowOnError extends boolean = false>(
  options: Options<RevokeApiKeyData, ThrowOnError>,
): RequestResult<RevokeApiKeyResponses, RevokeApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    RevokeApiKeyResponses,
    RevokeApiKeyErrors,
    ThrowOnError
  >({
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/api/keys/{id}",
    ...options,
  });

/**
 * Reset Api Key
 */
export const resetApiKey = <ThrowOnError extends boolean = false>(
  options: Options<ResetApiKeyData, ThrowOnError>,
): RequestResult<ResetApiKeyResponses, ResetApiKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ResetApiKeyResponses,
    ResetApiKeyErrors,
    ThrowOnError
  >({
    responseTransformer: resetApiKeyResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/api/keys/{id}/reset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Active Tasks
 */
export const listActiveTasks = <ThrowOnError extends boolean = false>(
  options?: Options<ListActiveTasksData, ThrowOnError>,
): RequestResult<ListActiveTasksResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListActiveTasksResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listActiveTasksResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/tasks/active",
    ...options,
  });

/**
 * List Task History
 */
export const listTaskHistory = <ThrowOnError extends boolean = false>(
  options?: Options<ListTaskHistoryData, ThrowOnError>,
): RequestResult<
  ListTaskHistoryResponses,
  ListTaskHistoryErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListTaskHistoryResponses,
    ListTaskHistoryErrors,
    ThrowOnError
  >({
    responseTransformer: listTaskHistoryResponseTransformer,
    security: [
      {
        key: "AccessManagerDependency",
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/general/tasks/history",
    ...options,
  });

/**
 * Get Opds Root
 */
export const opdsRoot = <ThrowOnError extends boolean = false>(
  options?: Options<OpdsRootData, ThrowOnError>,
): RequestResult<OpdsRootResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<OpdsRootResponses, unknown, ThrowOnError>({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/",
    ...options,
  });

/**
 * Get Opds All Files
 */
export const opdsAll = <ThrowOnError extends boolean = false>(
  options?: Options<OpdsAllData, ThrowOnError>,
): RequestResult<OpdsAllResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<OpdsAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/all",
    ...options,
  });

/**
 * Get Opds Opensearch
 */
export const opdsOpenSearch = <ThrowOnError extends boolean = false>(
  options?: Options<OpdsOpenSearchData, ThrowOnError>,
): RequestResult<OpdsOpenSearchResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    OpdsOpenSearchResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/opensearch.xml",
    ...options,
  });

/**
 * Get Opds Search
 */
export const opdsSearch = <ThrowOnError extends boolean = false>(
  options?: Options<OpdsSearchData, ThrowOnError>,
): RequestResult<OpdsSearchResponses, OpdsSearchErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    OpdsSearchResponses,
    OpdsSearchErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/search",
    ...options,
  });

/**
 * Get Opds Shelf
 */
export const opdsShelf = <ThrowOnError extends boolean = false>(
  options?: Options<OpdsShelfData, ThrowOnError>,
): RequestResult<OpdsShelfResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<OpdsShelfResponses, unknown, ThrowOnError>({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/shelf",
    ...options,
  });

/**
 * Get Opds Collections
 */
export const opdsCollections = <ThrowOnError extends boolean = false>(
  options?: Options<OpdsCollectionsData, ThrowOnError>,
): RequestResult<OpdsCollectionsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    OpdsCollectionsResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/collections",
    ...options,
  });

/**
 * Get Opds Collection
 */
export const opdsCollection = <ThrowOnError extends boolean = false>(
  options: Options<OpdsCollectionData, ThrowOnError>,
): RequestResult<OpdsCollectionResponses, OpdsCollectionErrors, ThrowOnError> =>
  (options.client ?? client).get<
    OpdsCollectionResponses,
    OpdsCollectionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/collections/{collection_id}",
    ...options,
  });

/**
 * Download Opds File
 */
export const getOpdsFile = <ThrowOnError extends boolean = false>(
  options: Options<GetOpdsFileData, ThrowOnError>,
): RequestResult<GetOpdsFileResponses, GetOpdsFileErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetOpdsFileResponses,
    GetOpdsFileErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/file/{id}.{ext}",
    ...options,
  });

/**
 * Download Opds Thumbnail
 */
export const getOpdsFileThumbnail = <ThrowOnError extends boolean = false>(
  options: Options<GetOpdsFileThumbnailData, ThrowOnError>,
): RequestResult<
  GetOpdsFileThumbnailResponses,
  GetOpdsFileThumbnailErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOpdsFileThumbnailResponses,
    GetOpdsFileThumbnailErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/v1/opds/file/{id}/thumbnail",
    ...options,
  });
