// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import {
  createAuthTokenResponseTransformer,
  getLibraryTreeResponseTransformer,
  refreshAuthTokenResponseTransformer,
} from "./transformers.gen";
import type {
  CreateAuthTokenData,
  CreateAuthTokenErrors,
  CreateAuthTokenResponses,
  CreateCollectionData,
  CreateCollectionErrors,
  CreateCollectionResponses,
  CreateFolderData,
  CreateFolderErrors,
  CreateFolderResponses,
  CreateSetupUserData,
  CreateSetupUserErrors,
  CreateSetupUserResponses,
  DeleteCollectionData,
  DeleteCollectionErrors,
  DeleteCollectionResponses,
  DeleteFileData,
  DeleteFileErrors,
  DeleteFileResponses,
  DeleteFolderData,
  DeleteFolderErrors,
  DeleteFolderResponses,
  DeleteTagData,
  DeleteTagErrors,
  DeleteTagResponses,
  GetAppStateData,
  GetAppStateResponses,
  GetAppStatusData,
  GetAppStatusResponses,
  GetCurrentSessionData,
  GetCurrentSessionResponses,
  GetFileData,
  GetFileDetailsData,
  GetFileDetailsErrors,
  GetFileDetailsResponses,
  GetFileErrors,
  GetFileResponses,
  GetFolderData,
  GetFolderErrors,
  GetFolderResponses,
  GetLibraryTreeData,
  GetLibraryTreeResponses,
  ListCollectionsData,
  ListCollectionsResponses,
  ListFilesData,
  ListFilesErrors,
  ListFilesResponses,
  ListFoldersData,
  ListFoldersResponses,
  ListTagsData,
  ListTagsResponses,
  ListUncategorizedFilesData,
  ListUncategorizedFilesResponses,
  PatchFileStateData,
  PatchFileStateErrors,
  PatchFileStateResponses,
  RefreshAuthTokenData,
  RefreshAuthTokenResponses,
  RevokeTokenData,
  RevokeTokenResponses,
  UpdateCollectionData,
  UpdateCollectionErrors,
  UpdateCollectionResponses,
  UpdateFileData,
  UpdateFileErrors,
  UpdateFileResponses,
  UpdateFolderData,
  UpdateFolderErrors,
  UpdateFolderResponses,
  UpdateTagData,
  UpdateTagErrors,
  UpdateTagResponses,
  UploadFileData,
  UploadFileErrors,
  UploadFileResponses,
} from "./types.gen";
import {
  zCreateAuthTokenData,
  zCreateAuthTokenResponse,
  zCreateCollectionData,
  zCreateFolderData,
  zCreateSetupUserData,
  zCreateSetupUserResponse,
  zDeleteCollectionData,
  zDeleteFileData,
  zDeleteFolderData,
  zDeleteTagData,
  zGetAppStateData,
  zGetAppStateResponse,
  zGetAppStatusData,
  zGetCurrentSessionData,
  zGetCurrentSessionResponse,
  zGetFileData,
  zGetFileDetailsData,
  zGetFileDetailsResponse,
  zGetFolderData,
  zGetFolderResponse,
  zGetLibraryTreeData,
  zGetLibraryTreeResponse,
  zListCollectionsData,
  zListCollectionsResponse,
  zListFilesData,
  zListFilesResponse,
  zListFoldersData,
  zListFoldersResponse,
  zListTagsData,
  zListTagsResponse,
  zListUncategorizedFilesData,
  zListUncategorizedFilesResponse,
  zPatchFileStateData,
  zRefreshAuthTokenData,
  zRefreshAuthTokenResponse,
  zRevokeTokenData,
  zUpdateCollectionData,
  zUpdateFileData,
  zUpdateFolderData,
  zUpdateTagData,
  zUploadFileData,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Current Session
 *
 * Get information about the current user session.
 */
export const getCurrentSession = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCurrentSessionResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetCurrentSessionData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetCurrentSessionResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/session",
    ...options,
  });

/**
 * Revoke Token
 *
 * Invalidate the access and refresh tokens
 */
export const revokeToken = <ThrowOnError extends boolean = false>(
  options?: Options<RevokeTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    RevokeTokenResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) => await zRevokeTokenData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/token",
    ...options,
  });

/**
 * Authenticate With Password
 *
 * Create access and refresh tokens using Basic Auth.
 */
export const createAuthToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateAuthTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAuthTokenResponses,
    CreateAuthTokenErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    requestValidator: async (data) =>
      await zCreateAuthTokenData.parseAsync(data),
    responseTransformer: createAuthTokenResponseTransformer,
    responseValidator: async (data) =>
      await zCreateAuthTokenResponse.parseAsync(data),
    url: "/api/v1/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Refresh Token
 *
 * Receive a new access token using the refresh token.
 */
export const refreshAuthToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshAuthTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshAuthTokenResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zRefreshAuthTokenData.parseAsync(data),
    responseTransformer: refreshAuthTokenResponseTransformer,
    responseValidator: async (data) =>
      await zRefreshAuthTokenResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/auth/refresh",
    ...options,
  });

/**
 * List Collections
 */
export const listCollections = <ThrowOnError extends boolean = false>(
  options?: Options<ListCollectionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListCollectionsResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zListCollectionsData.parseAsync(data),
    responseValidator: async (data) =>
      await zListCollectionsResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/collections",
    ...options,
  });

/**
 * Create Collection
 */
export const createCollection = <ThrowOnError extends boolean = false>(
  options: Options<CreateCollectionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCollectionResponses,
    CreateCollectionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zCreateCollectionData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/collections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Collection
 */
export const deleteCollection = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCollectionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteCollectionResponses,
    DeleteCollectionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zDeleteCollectionData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/collections/{id}",
    ...options,
  });

/**
 * Update Collection
 */
export const updateCollection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCollectionData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateCollectionResponses,
    UpdateCollectionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zUpdateCollectionData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/collections/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Folder
 */
export const deleteFolder = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFolderData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteFolderResponses,
    DeleteFolderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zDeleteFolderData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/folders/{id}",
    ...options,
  });

/**
 * Get Folder
 */
export const getFolder = <ThrowOnError extends boolean = false>(
  options: Options<GetFolderData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetFolderResponses,
    GetFolderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zGetFolderData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetFolderResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/folders/{id}",
    ...options,
  });

/**
 * Update Folder
 */
export const updateFolder = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFolderData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateFolderResponses,
    UpdateFolderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zUpdateFolderData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/folders/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Folders
 */
export const listFolders = <ThrowOnError extends boolean = false>(
  options?: Options<ListFoldersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListFoldersResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListFoldersData.parseAsync(data),
    responseValidator: async (data) =>
      await zListFoldersResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/folders",
    ...options,
  });

/**
 * Create Folder
 */
export const createFolder = <ThrowOnError extends boolean = false>(
  options: Options<CreateFolderData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateFolderResponses,
    CreateFolderErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zCreateFolderData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/folders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete File
 */
export const deleteFile = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFileData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteFileResponses,
    DeleteFileErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zDeleteFileData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files/{id}",
    ...options,
  });

/**
 * Get File Details
 */
export const getFileDetails = <ThrowOnError extends boolean = false>(
  options: Options<GetFileDetailsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetFileDetailsResponses,
    GetFileDetailsErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetFileDetailsData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetFileDetailsResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files/{id}",
    ...options,
  });

/**
 * Update File
 */
export const updateFile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateFileData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateFileResponses,
    UpdateFileErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zUpdateFileData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Patch File State
 */
export const patchFileState = <ThrowOnError extends boolean = false>(
  options: Options<PatchFileStateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PatchFileStateResponses,
    PatchFileStateErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zPatchFileStateData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files/{id}/state",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Library Tree
 */
export const getLibraryTree = <ThrowOnError extends boolean = false>(
  options?: Options<GetLibraryTreeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetLibraryTreeResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zGetLibraryTreeData.parseAsync(data),
    responseTransformer: getLibraryTreeResponseTransformer,
    responseValidator: async (data) =>
      await zGetLibraryTreeResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/tree",
    ...options,
  });

/**
 * List Tags
 */
export const listTags = <ThrowOnError extends boolean = false>(
  options?: Options<ListTagsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListTagsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListTagsData.parseAsync(data),
    responseValidator: async (data) => await zListTagsResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/tags",
    ...options,
  });

/**
 * Delete Tag
 */
export const deleteTag = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTagData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTagResponses,
    DeleteTagErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zDeleteTagData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/tags/{id}",
    ...options,
  });

/**
 * Update Tag
 */
export const updateTag = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTagData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateTagResponses,
    UpdateTagErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zUpdateTagData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/tags/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Uncategorized Files
 */
export const listUncategorizedFiles = <ThrowOnError extends boolean = false>(
  options?: Options<ListUncategorizedFilesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListUncategorizedFilesResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zListUncategorizedFilesData.parseAsync(data),
    responseValidator: async (data) =>
      await zListUncategorizedFilesResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files/uncategorized",
    ...options,
  });

/**
 * List Files
 */
export const listFiles = <ThrowOnError extends boolean = false>(
  options?: Options<ListFilesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListFilesResponses,
    ListFilesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await zListFilesData.parseAsync(data),
    responseValidator: async (data) =>
      await zListFilesResponse.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files",
    ...options,
  });

/**
 * Upload File
 */
export const uploadFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadFileData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UploadFileResponses,
    UploadFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    requestValidator: async (data) => await zUploadFileData.parseAsync(data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/library/files/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Get File
 */
export const getFile = <ThrowOnError extends boolean = false>(
  options: Options<GetFileData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetFileResponses, GetFileErrors, ThrowOnError>(
    {
      requestValidator: async (data) => await zGetFileData.parseAsync(data),
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/library/files/{id}/download",
      ...options,
    },
  );

/**
 * State
 *
 * Get current app state
 */
export const getAppState = <ThrowOnError extends boolean = false>(
  options?: Options<GetAppStateData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAppStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAppStateData.parseAsync(data),
    responseValidator: async (data) =>
      await zGetAppStateResponse.parseAsync(data),
    url: "/api/v1/setup/state",
    ...options,
  });

/**
 * Setup User
 *
 * Create initial app admin user
 */
export const createSetupUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateSetupUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSetupUserResponses,
    CreateSetupUserErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await zCreateSetupUserData.parseAsync(data),
    responseValidator: async (data) =>
      await zCreateSetupUserResponse.parseAsync(data),
    url: "/api/v1/setup/user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Status
 *
 * liveness / readiness probe
 */
export const getAppStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetAppStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAppStatusResponses, unknown, ThrowOnError>(
    {
      requestValidator: async (data) =>
        await zGetAppStatusData.parseAsync(data),
      url: "/api/v1/setup/status",
      ...options,
    },
  );
