// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateApiKeyResponse,
  CreateAuthTokenResponse,
  GetCollectionResponse,
  GetFileDetailsResponse,
  GetFileStateResponse,
  GetLibraryTreeResponse,
  ListAnnotationsResponse,
  ListApiKeysResponse,
  ListFilesResponse,
  RefreshAuthTokenResponse,
  ResetApiKeyResponse,
  SearchFilesResponse,
} from "./types.gen";

const accessTokenSchemaResponseTransformer = (data: any) => {
  data.expires = new Date(data.expires);
  return data;
};

export const createAuthTokenResponseTransformer = async (
  data: any,
): Promise<CreateAuthTokenResponse> => {
  data = accessTokenSchemaResponseTransformer(data);
  return data;
};

export const refreshAuthTokenResponseTransformer = async (
  data: any,
): Promise<RefreshAuthTokenResponse> => {
  data = accessTokenSchemaResponseTransformer(data);
  return data;
};

const fileStateResponseSchemaResponseTransformer = (data: any) => {
  if (data.last_read_at) {
    data.last_read_at = new Date(data.last_read_at);
  }
  return data;
};

const fileResponseSchemaResponseTransformer = (data: any) => {
  data.state = fileStateResponseSchemaResponseTransformer(data.state);
  return data;
};

const collectionWithDetailsResponseSchemaResponseTransformer = (data: any) => {
  if (data.files) {
    data.files = data.files.map((item: any) =>
      fileResponseSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const getCollectionResponseTransformer = async (
  data: any,
): Promise<GetCollectionResponse> => {
  data = collectionWithDetailsResponseSchemaResponseTransformer(data);
  return data;
};

export const getFileDetailsResponseTransformer = async (
  data: any,
): Promise<GetFileDetailsResponse> => {
  data = fileResponseSchemaResponseTransformer(data);
  return data;
};

export const getFileStateResponseTransformer = async (
  data: any,
): Promise<GetFileStateResponse> => {
  data = data.map((item: any) =>
    fileStateResponseSchemaResponseTransformer(item),
  );
  return data;
};

const libraryTreeNodeSchemaResponseTransformer = (data: any) => {
  if (data.children) {
    data.children = data.children.map((item: any) =>
      libraryTreeNodeSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const getLibraryTreeResponseTransformer = async (
  data: any,
): Promise<GetLibraryTreeResponse> => {
  data = data.map((item: any) =>
    libraryTreeNodeSchemaResponseTransformer(item),
  );
  return data;
};

export const listFilesResponseTransformer = async (
  data: any,
): Promise<ListFilesResponse> => {
  data = data.map((item: any) => fileResponseSchemaResponseTransformer(item));
  return data;
};

const annotationResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const listAnnotationsResponseTransformer = async (
  data: any,
): Promise<ListAnnotationsResponse> => {
  data = data.map((item: any) =>
    annotationResponseSchemaResponseTransformer(item),
  );
  return data;
};

const searchHitResponseSchemaResponseTransformer = (data: any) => {
  if (data.annotation) {
    data.annotation = annotationResponseSchemaResponseTransformer(
      data.annotation,
    );
  }
  return data;
};

const fileSearchResponseSchemaResponseTransformer = (data: any) => {
  data.file = fileResponseSchemaResponseTransformer(data.file);
  data.hits = data.hits.map((item: any) =>
    searchHitResponseSchemaResponseTransformer(item),
  );
  return data;
};

export const searchFilesResponseTransformer = async (
  data: any,
): Promise<SearchFilesResponse> => {
  data = data.map((item: any) =>
    fileSearchResponseSchemaResponseTransformer(item),
  );
  return data;
};

const apiKeyResponseSchemaResponseTransformer = (data: any) => {
  data.expires_at = new Date(data.expires_at);
  return data;
};

export const listApiKeysResponseTransformer = async (
  data: any,
): Promise<ListApiKeysResponse> => {
  data = data.map((item: any) => apiKeyResponseSchemaResponseTransformer(item));
  return data;
};

const apiKeyCreateResultResponseSchemaResponseTransformer = (data: any) => {
  data.expires_at = new Date(data.expires_at);
  return data;
};

export const createApiKeyResponseTransformer = async (
  data: any,
): Promise<CreateApiKeyResponse> => {
  data = apiKeyCreateResultResponseSchemaResponseTransformer(data);
  return data;
};

export const resetApiKeyResponseTransformer = async (
  data: any,
): Promise<ResetApiKeyResponse> => {
  data = apiKeyCreateResultResponseSchemaResponseTransformer(data);
  return data;
};
