// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5173" | (string & {});
};

/**
 * AccessToken
 *
 * API access token.
 */
export type AccessToken = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
  /**
   * Expires
   */
  expires: Date;
};

/**
 * AppStateResponse
 */
export type AppStateResponse = {
  /**
   * Is Initial User Created
   */
  is_initial_user_created?: boolean;
  /**
   * Is Setup Complete
   *
   * Check if the setup is complete
   */
  readonly is_setup_complete: boolean;
};

/**
 * AuthProviderResponse
 */
export type AuthProviderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Is Protected
   */
  is_protected: boolean;
};

/**
 * Body_CreateAuthToken
 */
export type BodyCreateAuthToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * Body_UploadFile
 */
export type BodyUploadFile = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Folder Id
   */
  folder_id: string;
  /**
   * Tags
   */
  tags?: Array<string>;
};

/**
 * CreateCollectionRequest
 */
export type CreateCollectionRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * CreateFolderRequest
 */
export type CreateFolderRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * FileResponse
 */
export type FileResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Folder Id
   */
  folder_id?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<TagResponse>;
  /**
   * Is Favorite
   */
  is_favorite: boolean;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Current Page
   */
  current_page: number;
  /**
   * Scale
   */
  scale: string;
  /**
   * Tags Name List
   */
  readonly tags_name_list: Array<string>;
};

/**
 * FolderResponse
 */
export type FolderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Files
   */
  files?: Array<FileResponse>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LibraryTreeNode
 */
export type LibraryTreeNode = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Children
   */
  children?: Array<LibraryTreeNode>;
  /**
   * Entity Type
   */
  entity_type: "collection" | "folder";
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * PatchFileStateRequest
 */
export type PatchFileStateRequest = {
  /**
   * Current Page
   */
  current_page?: number | null;
  /**
   * Scale
   */
  scale?: string | null;
};

/**
 * RoleResponse
 */
export type RoleResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Scopes
   */
  scopes: string;
  /**
   * Scope List
   */
  readonly scope_list: Array<string>;
};

/**
 * SetupUser
 *
 * Create initial application user
 */
export type SetupUser = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * TagDetailResponse
 */
export type TagDetailResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
  /**
   * File Count
   */
  file_count: number;
};

/**
 * TagResponse
 */
export type TagResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
};

/**
 * UpdateCollectionRequest
 */
export type UpdateCollectionRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * UpdateFileRequest
 */
export type UpdateFileRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Folder Id
   */
  folder_id?: string | null;
  /**
   * Is Favorite
   */
  is_favorite?: boolean;
};

/**
 * UpdateFolderRequest
 */
export type UpdateFolderRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * UpdateTagRequest
 */
export type UpdateTagRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Auth Provider Id
   */
  auth_provider_id: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
  role: RoleResponse;
  auth_provider: AuthProviderResponse;
};

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export type UserSessionResponse = {
  /**
   * User Id
   */
  user_id: string;
  user: UserResponse;
  /**
   * Session Id
   */
  session_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * AppStateResponse
 */
export type AppStateResponseWritable = {
  /**
   * Is Initial User Created
   */
  is_initial_user_created?: boolean;
};

/**
 * FileResponse
 */
export type FileResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Folder Id
   */
  folder_id?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<TagResponse>;
  /**
   * Is Favorite
   */
  is_favorite: boolean;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Current Page
   */
  current_page: number;
  /**
   * Scale
   */
  scale: string;
};

/**
 * FolderResponse
 */
export type FolderResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Files
   */
  files?: Array<FileResponseWritable>;
};

/**
 * RoleResponse
 */
export type RoleResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Scopes
   */
  scopes: string;
};

/**
 * SetupUser
 *
 * Create initial application user
 */
export type SetupUserWritable = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
  /**
   * Name
   */
  name: string;
};

/**
 * UserResponse
 */
export type UserResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Auth Provider Id
   */
  auth_provider_id: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
  role: RoleResponseWritable;
  auth_provider: AuthProviderResponse;
};

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export type UserSessionResponseWritable = {
  /**
   * User Id
   */
  user_id: string;
  user: UserResponseWritable;
  /**
   * Session Id
   */
  session_id: string;
};

export type GetCurrentSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/session";
};

export type GetCurrentSessionResponses = {
  /**
   * Successful Response
   */
  200: UserSessionResponse;
};

export type GetCurrentSessionResponse =
  GetCurrentSessionResponses[keyof GetCurrentSessionResponses];

export type RevokeTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type RevokeTokenResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateAuthTokenData = {
  body: BodyCreateAuthToken;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type CreateAuthTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAuthTokenError =
  CreateAuthTokenErrors[keyof CreateAuthTokenErrors];

export type CreateAuthTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type CreateAuthTokenResponse =
  CreateAuthTokenResponses[keyof CreateAuthTokenResponses];

export type RefreshAuthTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/refresh";
};

export type RefreshAuthTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type RefreshAuthTokenResponse =
  RefreshAuthTokenResponses[keyof RefreshAuthTokenResponses];

export type CreateCollectionData = {
  body: CreateCollectionRequest;
  path?: never;
  query?: never;
  url: "/api/v1/library/collections";
};

export type CreateCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCollectionError =
  CreateCollectionErrors[keyof CreateCollectionErrors];

export type CreateCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteCollectionData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type DeleteCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCollectionError =
  DeleteCollectionErrors[keyof DeleteCollectionErrors];

export type DeleteCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateCollectionData = {
  body: UpdateCollectionRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type UpdateCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCollectionError =
  UpdateCollectionErrors[keyof UpdateCollectionErrors];

export type UpdateCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteFolderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/folders/{id}";
};

export type DeleteFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFolderError = DeleteFolderErrors[keyof DeleteFolderErrors];

export type DeleteFolderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFolderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/folders/{id}";
};

export type GetFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFolderError = GetFolderErrors[keyof GetFolderErrors];

export type GetFolderResponses = {
  /**
   * Successful Response
   */
  200: FolderResponse;
};

export type GetFolderResponse = GetFolderResponses[keyof GetFolderResponses];

export type UpdateFolderData = {
  body: UpdateFolderRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/folders/{id}";
};

export type UpdateFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFolderError = UpdateFolderErrors[keyof UpdateFolderErrors];

export type UpdateFolderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListFoldersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/folders";
};

export type ListFoldersResponses = {
  /**
   * Response Listfolders
   *
   * Successful Response
   */
  200: Array<FolderResponse>;
};

export type ListFoldersResponse =
  ListFoldersResponses[keyof ListFoldersResponses];

export type CreateFolderData = {
  body: CreateFolderRequest;
  path?: never;
  query?: never;
  url: "/api/v1/library/folders";
};

export type CreateFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type DeleteFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileDetailsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type GetFileDetailsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileDetailsError =
  GetFileDetailsErrors[keyof GetFileDetailsErrors];

export type GetFileDetailsResponses = {
  /**
   * Successful Response
   */
  200: FileResponse;
};

export type GetFileDetailsResponse =
  GetFileDetailsResponses[keyof GetFileDetailsResponses];

export type UpdateFileData = {
  body: UpdateFileRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type UpdateFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFileError = UpdateFileErrors[keyof UpdateFileErrors];

export type UpdateFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PatchFileStateData = {
  body: PatchFileStateRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/state";
};

export type PatchFileStateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PatchFileStateError =
  PatchFileStateErrors[keyof PatchFileStateErrors];

export type PatchFileStateResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetLibraryTreeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/tree";
};

export type GetLibraryTreeResponses = {
  /**
   * Response Getlibrarytree
   *
   * Successful Response
   */
  200: Array<LibraryTreeNode>;
};

export type GetLibraryTreeResponse =
  GetLibraryTreeResponses[keyof GetLibraryTreeResponses];

export type ListTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/tags";
};

export type ListTagsResponses = {
  /**
   * Response Listtags
   *
   * Successful Response
   */
  200: Array<TagDetailResponse>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type DeleteTagData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/tags/{id}";
};

export type DeleteTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateTagData = {
  body: UpdateTagRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/tags/{id}";
};

export type UpdateTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListUncategorizedFilesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/files/uncategorized";
};

export type ListUncategorizedFilesResponses = {
  /**
   * Response Listuncategorizedfiles
   *
   * Successful Response
   */
  200: Array<FileResponse>;
};

export type ListUncategorizedFilesResponse =
  ListUncategorizedFilesResponses[keyof ListUncategorizedFilesResponses];

export type ListFilesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Is Favorite
     */
    is_favorite?: boolean | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Text
     */
    text?: Array<string> | null;
  };
  url: "/api/v1/library/files";
};

export type ListFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
  /**
   * Response Listfiles
   *
   * Successful Response
   */
  200: Array<FileResponse>;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type UploadFileData = {
  body: BodyUploadFile;
  path?: never;
  query?: never;
  url: "/api/v1/library/files/upload";
};

export type UploadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/download";
};

export type GetFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAppStateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/setup/state";
};

export type GetAppStateResponses = {
  /**
   * Successful Response
   */
  200: AppStateResponse;
};

export type GetAppStateResponse =
  GetAppStateResponses[keyof GetAppStateResponses];

export type CreateSetupUserData = {
  body: SetupUserWritable;
  path?: never;
  query?: never;
  url: "/api/v1/setup/user";
};

export type CreateSetupUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSetupUserError =
  CreateSetupUserErrors[keyof CreateSetupUserErrors];

export type CreateSetupUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type CreateSetupUserResponse =
  CreateSetupUserResponses[keyof CreateSetupUserResponses];
