// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5173" | (string & {});
};

/**
 * AccessToken
 *
 * API access token.
 */
export type AccessToken = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
  /**
   * Expires
   */
  expires: Date;
};

/**
 * AnnotationResponse
 */
export type AnnotationResponse = {
  /**
   * Page
   */
  page: number;
  /**
   * Body
   */
  body: string;
  /**
   * Color
   */
  color: string;
  /**
   * Excerpt
   */
  excerpt: string;
  /**
   * Rects
   */
  rects: Array<NormalizedRect>;
  /**
   * Label
   *
   * User-set identifier, used to cross-reference
   */
  label?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Author Id
   */
  author_id?: string | null;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Author Name
   */
  author_name?: string | null;
};

/**
 * ApiKeyCreateRequest
 */
export type ApiKeyCreateRequest = {
  /**
   * Description
   */
  description: string;
  /**
   * Expires At
   */
  expires_at: Date;
  /**
   * User Id
   */
  user_id: string;
  scopes: Scopes;
};

/**
 * ApiKeyCreateResultResponse
 */
export type ApiKeyCreateResultResponse = {
  /**
   * Token
   */
  token: string;
  /**
   * Expires At
   */
  expires_at: Date;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * ApiKeyPersonalCreate
 */
export type ApiKeyPersonalCreate = {
  /**
   * Description
   */
  description: string;
  /**
   * Expires At
   */
  expires_at: Date;
  scopes: Scopes;
};

/**
 * ApiKeyResetRequest
 */
export type ApiKeyResetRequest = {
  /**
   * Expires At
   */
  expires_at: Date;
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Description
   */
  description: string;
  /**
   * Expires At
   */
  expires_at: Date;
  /**
   * Is Revoked
   */
  is_revoked: boolean;
  /**
   * User Id
   */
  user_id: string;
  scopes: Scopes;
  user?: UserSummaryResponse | null;
  /**
   * Scopes Str
   */
  readonly scopes_str: string;
  /**
   * Is Expired
   */
  readonly is_expired: boolean;
};

/**
 * AppStateResponse
 */
export type AppStateResponse = {
  /**
   * Is Initial User Created
   */
  is_initial_user_created?: boolean;
  /**
   * Sso Servers
   */
  sso_servers?: Array<SsoConfigResponse>;
  auto_login_sso_server?: SsoConfigResponse | null;
  /**
   * Opds Url
   */
  opds_url: string;
  /**
   * Is Setup Complete
   *
   * Check if the setup is complete
   */
  readonly is_setup_complete: boolean;
};

/**
 * AssignmentResponse
 */
export type AssignmentResponse = {
  /**
   * Id
   */
  id: string;
  user: UserSummaryResponse;
  /**
   * Inherited From
   */
  inherited_from?: string | null;
  /**
   * Permission
   */
  permission: "owner" | "read" | "modify";
  /**
   * Is Read Only By Current User
   *
   * Whether current user can only read this assignment
   */
  readonly is_read_only_by_current_user: boolean;
};

/**
 * AuthProviderOidcCreateRequest
 */
export type AuthProviderOidcCreateRequest = {
  /**
   * Name
   */
  name: string;
};

/**
 * AuthProviderOidcResponse
 */
export type AuthProviderOidcResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Entity Type
   */
  entity_type: "OIDC";
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
  /**
   * Group Claim Name
   */
  group_claim_name: string;
  /**
   * Auto Discovery Url
   */
  auto_discovery_url: string;
  /**
   * Additional Scopes
   */
  additional_scopes: string;
  /**
   * Auto Login
   */
  auto_login: boolean;
  /**
   * Group Claim Rules
   */
  group_claim_rules: Array<OidcGroupRuleOutput>;
  /**
   * Redirect Url
   *
   * URL to which the OIDC provider will redirect after successful authentication
   */
  redirect_url: string;
  /**
   * Authorize Url
   *
   * URL to which the frontend should redirect the user to initiate OIDC authentication
   */
  authorize_url: string;
};

/**
 * AuthProviderOidcUpdateRequest
 */
export type AuthProviderOidcUpdateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Is Enabled
   */
  is_enabled?: boolean;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Auto Discovery Url
   */
  auto_discovery_url: string;
  /**
   * Additional Scopes
   */
  additional_scopes?: string;
  /**
   * Group Claim Name
   */
  group_claim_name?: string;
  /**
   * Group Claim Rules
   */
  group_claim_rules?: Array<OidcGroupRuleInput>;
  /**
   * Auto Login
   */
  auto_login?: boolean;
};

/**
 * AuthProviderResponse
 *
 * Generic response model for authentication providers.
 *
 * Specific provider types may have additional parameters, but all share these common parameters.
 */
export type AuthProviderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Is Protected
   */
  is_protected: boolean;
};

/**
 * AuthorResponse
 */
export type AuthorResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
};

/**
 * Body_CreateAuthToken
 */
export type BodyCreateAuthToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * Body_UploadFile
 */
export type BodyUploadFile = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Collection Id
   */
  collection_id: string;
  /**
   * Tags
   */
  tags?: Array<string>;
};

/**
 * CollectionResponse
 */
export type CollectionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Entity Type
   */
  entity_type: "folder" | "group";
};

/**
 * CollectionWithDetailsResponse
 */
export type CollectionWithDetailsResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Entity Type
   */
  entity_type: "folder" | "group";
  owner: UserSummaryResponse;
  /**
   * Is Shared With Current User
   */
  readonly is_shared_with_current_user: boolean;
  /**
   * Is Read Only By Current User
   *
   * Whether current user can only read this collection
   */
  readonly is_read_only_by_current_user: boolean;
};

/**
 * CreateAnnotationRequest
 */
export type CreateAnnotationRequest = {
  /**
   * Page
   */
  page: number;
  /**
   * Body
   */
  body: string;
  /**
   * Color
   */
  color: string;
  /**
   * Excerpt
   */
  excerpt: string;
  /**
   * Rects
   */
  rects: Array<NormalizedRect>;
  /**
   * Label
   *
   * User-set identifier, used to cross-reference
   */
  label?: string | null;
};

/**
 * CreateCollectionRequest
 */
export type CreateCollectionRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Entity Type
   */
  entity_type: "folder" | "group";
};

/**
 * CredentialsReset
 *
 * This model is used to reset (by admin) user credentials.
 */
export type CredentialsReset = {
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
};

/**
 * CredentialsUpdate
 *
 * This model is used to change user credentials.
 */
export type CredentialsUpdate = {
  /**
   * Password Old
   */
  password_old: string;
  /**
   * Password New
   */
  password_new: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
};

/**
 * DetailsUpdate
 */
export type DetailsUpdate = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * FileResponse
 */
export type FileResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Collection Id
   */
  collection_id: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Tags
   */
  tags?: Array<TagResponse>;
  /**
   * Authors
   */
  authors?: Array<AuthorResponse>;
  /**
   * Published
   */
  published?: Date | null;
  /**
   * File Size
   */
  file_size: number;
  /**
   * Content Type
   */
  content_type: string;
  /**
   * Original Name
   */
  original_name: string;
  /**
   * File Hash
   */
  file_hash?: string | null;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
  state: FileStateResponse;
  /**
   * Tags Name List
   */
  readonly tags_name_list: Array<string>;
  /**
   * Is Read Only By Current User
   *
   * Whether current user can only read this file
   */
  readonly is_read_only_by_current_user: boolean;
};

/**
 * FileSearchResponse
 */
export type FileSearchResponse = {
  file: FileResponse;
  /**
   * Hits
   */
  hits: Array<SearchHitResponse>;
  /**
   * Score
   */
  readonly score: "weak" | "good" | "strong";
};

/**
 * FileStateResponse
 */
export type FileStateResponse = {
  /**
   * Is Favorite
   */
  is_favorite: boolean;
  /**
   * Current Page
   */
  current_page: number;
  /**
   * Scale
   */
  scale: string;
  status: FileStatusEnum;
  /**
   * Last Read At
   */
  last_read_at?: Date | null;
};

/**
 * FileStatusEnum
 */
export const FileStatusEnum = {
  UNREAD: "unread",
  READING: "reading",
  ON_HOLD: "on_hold",
  DROPPED: "dropped",
  READ: "read",
  WANT_TO_READ: "want_to_read",
} as const;

/**
 * FileStatusEnum
 */
export type FileStatusEnum =
  (typeof FileStatusEnum)[keyof typeof FileStatusEnum];

/**
 * FragmentType
 */
export const FragmentType = {
  TITLE: "title",
  DESCRIPTION: "description",
  PAGE: "page",
  ANNOTATION: "annotation",
  LABEL: "label",
} as const;

/**
 * FragmentType
 */
export type FragmentType = (typeof FragmentType)[keyof typeof FragmentType];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InviteToCollectionRequest
 */
export type InviteToCollectionRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Permission
   */
  permission: "read" | "modify";
};

/**
 * LibraryTreeNode
 */
export type LibraryTreeNode = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Children
   */
  children?: Array<LibraryTreeNode>;
  /**
   * Entity Type
   */
  entity_type: "group" | "folder";
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Is Shared
   */
  readonly is_shared: boolean;
  /**
   * Is Read Only By Current User
   */
  readonly is_read_only_by_current_user: boolean;
};

/**
 * NormalizedRect
 *
 * All values are fractions (0..1) of the .page element's box,
 * so they survive zoom / rotate without recomputation.
 */
export type NormalizedRect = {
  /**
   * Top
   */
  top: number;
  /**
   * Left
   */
  left: number;
  /**
   * Width
   */
  width: number;
  /**
   * Height
   */
  height: number;
};

/**
 * OidcGroupRule
 */
export type OidcGroupRuleInput = {
  /**
   * Group
   *
   * Name of the group as provided by the OIDC provider
   */
  group: string;
  /**
   * Role Id
   *
   * ID of the role to assign to users in this group
   */
  role_id: string;
};

/**
 * OidcGroupRule
 */
export type OidcGroupRuleOutput = {
  /**
   * Group
   *
   * Name of the group as provided by the OIDC provider
   */
  group: string;
  /**
   * Role Id
   *
   * ID of the role to assign to users in this group
   */
  role_id: string;
};

/**
 * PaginatedResponse[TaskHistoryResponse]
 */
export type PaginatedResponseTaskHistoryResponse = {
  /**
   * Results
   */
  results: Array<TaskHistoryResponse>;
  /**
   * Row Count
   */
  row_count: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Page Index
   */
  page_index?: number;
};

/**
 * PatchAnnotationRequest
 */
export type PatchAnnotationRequest = {
  /**
   * Label
   *
   * User-set identifier, used to cross-reference
   */
  label?: string | null;
  /**
   * Body
   */
  body?: string | null;
  /**
   * Color
   */
  color?: string | null;
};

/**
 * PatchFileStateRequest
 */
export type PatchFileStateRequest = {
  /**
   * Current Page
   */
  current_page?: number | null;
  /**
   * Scale
   */
  scale?: string | null;
  /**
   * Is Favorite
   */
  is_favorite?: boolean | null;
  status?: FileStatusEnum | null;
};

/**
 * ResourcePermissionResponse
 */
export type ResourcePermissionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Name
   */
  name: string;
  /**
   * Assignments
   */
  assignments: Array<AssignmentResponse>;
};

/**
 * RevokeResponse
 */
export type RevokeResponse = {
  /**
   * Redirect Url
   */
  redirect_url?: string | null;
};

/**
 * RoleResponse
 */
export type RoleResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Entity Type
   */
  entity_type: string;
  scopes: Scopes;
  /**
   * Scopes Str
   */
  readonly scopes_str: string;
};

/**
 * Scopes
 */
export type Scopes = Array<string>;

/**
 * SearchHitResponse
 */
export type SearchHitResponse = {
  /**
   * Snippet
   */
  snippet: string;
  /**
   * Page Number
   */
  page_number?: number | null;
  fragment_type: FragmentType;
  /**
   * Score
   *
   * Normalized relevance, higher = better
   */
  score: number;
  annotation?: AnnotationResponse | null;
  /**
   * Field
   */
  field?: string | null;
};

/**
 * SetupUser
 *
 * Create initial application user
 */
export type SetupUser = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * SsoConfigResponse
 */
export type SsoConfigResponse = {
  /**
   * Url
   */
  url: string;
  /**
   * Is Auto Login Enabled
   */
  is_auto_login_enabled: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * TagResponse
 */
export type TagResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
};

/**
 * TagWithDetailsResponse
 */
export type TagWithDetailsResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
  /**
   * File Count
   */
  file_count: number;
};

/**
 * TaskActiveResponse
 */
export type TaskActiveResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  status: TaskStatusEnum;
  /**
   * Attempt
   */
  attempt: number;
  /**
   * Subject
   */
  subject: string | null;
  /**
   * Progress
   */
  progress?: number | null;
  /**
   * Detail
   */
  detail: string | null;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
  /**
   * Display Name
   */
  readonly display_name: string;
};

/**
 * TaskHistoryResponse
 */
export type TaskHistoryResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  status: TaskStatusEnum;
  /**
   * Started At
   */
  started_at: Date;
  /**
   * Duration Ms
   */
  duration_ms: number | null;
  /**
   * Error
   */
  error: string | null;
  /**
   * Subject
   */
  subject: string | null;
  /**
   * Display Name
   */
  readonly display_name: string;
  /**
   * Display Duration
   */
  readonly display_duration: string;
};

/**
 * TaskStatusEnum
 */
export const TaskStatusEnum = {
  PENDING: "pending",
  RUNNING: "running",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  CANCELLED: "cancelled",
  INTERRUPTED: "interrupted",
} as const;

/**
 * TaskStatusEnum
 */
export type TaskStatusEnum =
  (typeof TaskStatusEnum)[keyof typeof TaskStatusEnum];

/**
 * UpdateCollectionPermissionRequest
 */
export type UpdateCollectionPermissionRequest = {
  /**
   * Permission
   */
  permission: "read" | "modify";
};

/**
 * UpdateCollectionRequest
 */
export type UpdateCollectionRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * UpdateFileRequest
 */
export type UpdateFileRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Collection Id
   */
  collection_id: string;
  /**
   * Authors
   */
  authors?: Array<string>;
  /**
   * Published
   */
  published?: Date | null;
};

/**
 * UpdateTagRequest
 */
export type UpdateTagRequest = {
  /**
   * Color
   */
  color: string;
};

/**
 * UserCreateRequest
 */
export type UserCreateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Auth Provider Id
   */
  auth_provider_id: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
  role: RoleResponse;
  /**
   * Is External
   */
  is_external: boolean;
  auth_provider: AuthProviderResponse;
};

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export type UserSessionResponse = {
  /**
   * User Id
   */
  user_id: string;
  user: UserResponse;
  /**
   * Session Id
   */
  session_id: string;
};

/**
 * UserSummaryResponse
 */
export type UserSummaryResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
};

/**
 * UserUpdateRequest
 */
export type UserUpdateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Description
   */
  description: string;
  /**
   * Expires At
   */
  expires_at: Date;
  /**
   * Is Revoked
   */
  is_revoked: boolean;
  /**
   * User Id
   */
  user_id: string;
  scopes: Scopes;
  user?: UserSummaryResponse | null;
};

/**
 * AppStateResponse
 */
export type AppStateResponseWritable = {
  /**
   * Is Initial User Created
   */
  is_initial_user_created?: boolean;
  /**
   * Sso Servers
   */
  sso_servers?: Array<SsoConfigResponse>;
  auto_login_sso_server?: SsoConfigResponse | null;
  /**
   * Opds Url
   */
  opds_url: string;
};

/**
 * AssignmentResponse
 */
export type AssignmentResponseWritable = {
  /**
   * Id
   */
  id: string;
  user: UserSummaryResponse;
  /**
   * Inherited From
   */
  inherited_from?: string | null;
  /**
   * Permission
   */
  permission: "owner" | "read" | "modify";
};

/**
 * AuthProviderOidcUpdateRequest
 */
export type AuthProviderOidcUpdateRequestWritable = {
  /**
   * Name
   */
  name: string;
  /**
   * Is Enabled
   */
  is_enabled?: boolean;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
  /**
   * Auto Discovery Url
   */
  auto_discovery_url: string;
  /**
   * Additional Scopes
   */
  additional_scopes?: string;
  /**
   * Group Claim Name
   */
  group_claim_name?: string;
  /**
   * Group Claim Rules
   */
  group_claim_rules?: Array<OidcGroupRuleInput>;
  /**
   * Auto Login
   */
  auto_login?: boolean;
};

/**
 * CollectionWithDetailsResponse
 */
export type CollectionWithDetailsResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Entity Type
   */
  entity_type: "folder" | "group";
  owner: UserSummaryResponse;
};

/**
 * FileResponse
 */
export type FileResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Collection Id
   */
  collection_id: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Tags
   */
  tags?: Array<TagResponse>;
  /**
   * Authors
   */
  authors?: Array<AuthorResponse>;
  /**
   * Published
   */
  published?: Date | null;
  /**
   * File Size
   */
  file_size: number;
  /**
   * Content Type
   */
  content_type: string;
  /**
   * Original Name
   */
  original_name: string;
  /**
   * File Hash
   */
  file_hash?: string | null;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
  state: FileStateResponse;
};

/**
 * FileSearchResponse
 */
export type FileSearchResponseWritable = {
  file: FileResponseWritable;
  /**
   * Hits
   */
  hits: Array<SearchHitResponse>;
};

/**
 * LibraryTreeNode
 */
export type LibraryTreeNodeWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Children
   */
  children?: Array<LibraryTreeNodeWritable>;
  /**
   * Entity Type
   */
  entity_type: "group" | "folder";
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * PaginatedResponse[TaskHistoryResponse]
 */
export type PaginatedResponseTaskHistoryResponseWritable = {
  /**
   * Results
   */
  results: Array<TaskHistoryResponseWritable>;
  /**
   * Row Count
   */
  row_count: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Page Index
   */
  page_index?: number;
};

/**
 * ResourcePermissionResponse
 */
export type ResourcePermissionResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Name
   */
  name: string;
  /**
   * Assignments
   */
  assignments: Array<AssignmentResponseWritable>;
};

/**
 * RoleResponse
 */
export type RoleResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Entity Type
   */
  entity_type: string;
  scopes: Scopes;
};

/**
 * SetupUser
 *
 * Create initial application user
 */
export type SetupUserWritable = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
  /**
   * Name
   */
  name: string;
};

/**
 * TaskActiveResponse
 */
export type TaskActiveResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  status: TaskStatusEnum;
  /**
   * Attempt
   */
  attempt: number;
  /**
   * Subject
   */
  subject: string | null;
  /**
   * Progress
   */
  progress?: number | null;
  /**
   * Detail
   */
  detail: string | null;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TaskHistoryResponse
 */
export type TaskHistoryResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  status: TaskStatusEnum;
  /**
   * Started At
   */
  started_at: Date;
  /**
   * Duration Ms
   */
  duration_ms: number | null;
  /**
   * Error
   */
  error: string | null;
  /**
   * Subject
   */
  subject: string | null;
};

/**
 * UserCreateRequest
 */
export type UserCreateRequestWritable = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
};

/**
 * UserResponse
 */
export type UserResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Auth Provider Id
   */
  auth_provider_id: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
  role: RoleResponseWritable;
  /**
   * Is External
   */
  is_external: boolean;
  auth_provider: AuthProviderResponse;
};

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export type UserSessionResponseWritable = {
  /**
   * User Id
   */
  user_id: string;
  user: UserResponseWritable;
  /**
   * Session Id
   */
  session_id: string;
};

export type GetCurrentSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/session";
};

export type GetCurrentSessionResponses = {
  /**
   * Successful Response
   */
  200: UserSessionResponse;
};

export type GetCurrentSessionResponse =
  GetCurrentSessionResponses[keyof GetCurrentSessionResponses];

export type RevokeTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type RevokeTokenResponses = {
  /**
   * Successful Response
   */
  200: RevokeResponse;
};

export type RevokeTokenResponse =
  RevokeTokenResponses[keyof RevokeTokenResponses];

export type CreateAuthTokenData = {
  body: BodyCreateAuthToken;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type CreateAuthTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAuthTokenError =
  CreateAuthTokenErrors[keyof CreateAuthTokenErrors];

export type CreateAuthTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type CreateAuthTokenResponse =
  CreateAuthTokenResponses[keyof CreateAuthTokenResponses];

export type RefreshAuthTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/refresh";
};

export type RefreshAuthTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type RefreshAuthTokenResponse =
  RefreshAuthTokenResponses[keyof RefreshAuthTokenResponses];

export type OidcLoginData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/auth/oidc/{id}";
};

export type OidcLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OidcLoginError = OidcLoginErrors[keyof OidcLoginErrors];

export type OidcLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OidcCallbackData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/auth/oidc/{id}/callback";
};

export type OidcCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OidcCallbackError = OidcCallbackErrors[keyof OidcCallbackErrors];

export type ListCollectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/collections";
};

export type ListCollectionsResponses = {
  /**
   * Response Listcollections
   *
   * Successful Response
   */
  200: Array<CollectionResponse>;
};

export type ListCollectionsResponse =
  ListCollectionsResponses[keyof ListCollectionsResponses];

export type CreateCollectionData = {
  body: CreateCollectionRequest;
  path?: never;
  query?: never;
  url: "/api/v1/library/collections";
};

export type CreateCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCollectionError =
  CreateCollectionErrors[keyof CreateCollectionErrors];

export type CreateCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListCollectionMoveTargetsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}/move-targets";
};

export type ListCollectionMoveTargetsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCollectionMoveTargetsError =
  ListCollectionMoveTargetsErrors[keyof ListCollectionMoveTargetsErrors];

export type ListCollectionMoveTargetsResponses = {
  /**
   * Response Listcollectionmovetargets
   *
   * Successful Response
   */
  200: Array<CollectionResponse>;
};

export type ListCollectionMoveTargetsResponse =
  ListCollectionMoveTargetsResponses[keyof ListCollectionMoveTargetsResponses];

export type DeleteCollectionData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type DeleteCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCollectionError =
  DeleteCollectionErrors[keyof DeleteCollectionErrors];

export type DeleteCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetCollectionData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type GetCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCollectionError = GetCollectionErrors[keyof GetCollectionErrors];

export type GetCollectionResponses = {
  /**
   * Successful Response
   */
  200: CollectionWithDetailsResponse;
};

export type GetCollectionResponse =
  GetCollectionResponses[keyof GetCollectionResponses];

export type UpdateCollectionData = {
  body: UpdateCollectionRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type UpdateCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCollectionError =
  UpdateCollectionErrors[keyof UpdateCollectionErrors];

export type UpdateCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetCollectionFilesData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: {
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Authors
     */
    authors?: Array<string> | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Status
     */
    status?: FileStatusEnum | null;
  };
  url: "/api/v1/library/collections/{id}/files";
};

export type GetCollectionFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCollectionFilesError =
  GetCollectionFilesErrors[keyof GetCollectionFilesErrors];

export type GetCollectionFilesResponses = {
  /**
   * Response Getcollectionfiles
   *
   * Successful Response
   */
  200: Array<FileResponse>;
};

export type GetCollectionFilesResponse =
  GetCollectionFilesResponses[keyof GetCollectionFilesResponses];

export type GetCollectionPermissionsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}/permissions";
};

export type GetCollectionPermissionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCollectionPermissionsError =
  GetCollectionPermissionsErrors[keyof GetCollectionPermissionsErrors];

export type GetCollectionPermissionsResponses = {
  /**
   * Successful Response
   */
  200: ResourcePermissionResponse;
};

export type GetCollectionPermissionsResponse =
  GetCollectionPermissionsResponses[keyof GetCollectionPermissionsResponses];

export type InviteToCollectionData = {
  body: InviteToCollectionRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}/permissions/invite";
};

export type InviteToCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InviteToCollectionError =
  InviteToCollectionErrors[keyof InviteToCollectionErrors];

export type InviteToCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteCollectionPermissionData = {
  body?: never;
  path: {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{collection_id}/permissions/{id}";
};

export type DeleteCollectionPermissionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCollectionPermissionError =
  DeleteCollectionPermissionErrors[keyof DeleteCollectionPermissionErrors];

export type DeleteCollectionPermissionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateCollectionPermissionData = {
  body: UpdateCollectionPermissionRequest;
  path: {
    /**
     * Collection Id
     */
    collection_id: string;
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{collection_id}/permissions/{id}";
};

export type UpdateCollectionPermissionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCollectionPermissionError =
  UpdateCollectionPermissionErrors[keyof UpdateCollectionPermissionErrors];

export type UpdateCollectionPermissionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListFileMoveTargetsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/move-targets";
};

export type ListFileMoveTargetsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListFileMoveTargetsError =
  ListFileMoveTargetsErrors[keyof ListFileMoveTargetsErrors];

export type ListFileMoveTargetsResponses = {
  /**
   * Response Listfilemovetargets
   *
   * Successful Response
   */
  200: Array<CollectionResponse>;
};

export type ListFileMoveTargetsResponse =
  ListFileMoveTargetsResponses[keyof ListFileMoveTargetsResponses];

export type DeleteFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type DeleteFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileDetailsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type GetFileDetailsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileDetailsError =
  GetFileDetailsErrors[keyof GetFileDetailsErrors];

export type GetFileDetailsResponses = {
  /**
   * Successful Response
   */
  200: FileResponse;
};

export type GetFileDetailsResponse =
  GetFileDetailsResponses[keyof GetFileDetailsResponses];

export type UpdateFileData = {
  body: UpdateFileRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type UpdateFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFileError = UpdateFileErrors[keyof UpdateFileErrors];

export type UpdateFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileStateData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/state";
};

export type GetFileStateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileStateError = GetFileStateErrors[keyof GetFileStateErrors];

export type GetFileStateResponses = {
  /**
   * Response Getfilestate
   *
   * Successful Response
   */
  200: Array<FileStateResponse>;
};

export type GetFileStateResponse =
  GetFileStateResponses[keyof GetFileStateResponses];

export type PatchFileStateData = {
  body: PatchFileStateRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/state";
};

export type PatchFileStateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PatchFileStateError =
  PatchFileStateErrors[keyof PatchFileStateErrors];

export type PatchFileStateResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetLibraryTreeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/tree";
};

export type GetLibraryTreeResponses = {
  /**
   * Response Getlibrarytree
   *
   * Successful Response
   */
  200: Array<LibraryTreeNode>;
};

export type GetLibraryTreeResponse =
  GetLibraryTreeResponses[keyof GetLibraryTreeResponses];

export type ListFilesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Is Favorite
     */
    is_favorite?: boolean | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
  };
  url: "/api/v1/library/files";
};

export type ListFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
  /**
   * Response Listfiles
   *
   * Successful Response
   */
  200: Array<FileResponse>;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type UploadFileData = {
  body: BodyUploadFile;
  path?: never;
  query?: never;
  url: "/api/v1/library/files/upload";
};

export type UploadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/download";
};

export type GetFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListAnnotationLabelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/files/annotations/labels";
};

export type ListAnnotationLabelsResponses = {
  /**
   * Response Listannotationlabels
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListAnnotationLabelsResponse =
  ListAnnotationLabelsResponses[keyof ListAnnotationLabelsResponses];

export type ListAnnotationsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/annotations";
};

export type ListAnnotationsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAnnotationsError =
  ListAnnotationsErrors[keyof ListAnnotationsErrors];

export type ListAnnotationsResponses = {
  /**
   * Response Listannotations
   *
   * Successful Response
   */
  200: Array<AnnotationResponse>;
};

export type ListAnnotationsResponse =
  ListAnnotationsResponses[keyof ListAnnotationsResponses];

export type CreateAnnotationData = {
  body: CreateAnnotationRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/annotations";
};

export type CreateAnnotationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAnnotationError =
  CreateAnnotationErrors[keyof CreateAnnotationErrors];

export type CreateAnnotationResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteAnnotationData = {
  body?: never;
  path: {
    /**
     * File Id
     */
    file_id: string;
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{file_id}/annotations/{id}";
};

export type DeleteAnnotationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAnnotationError =
  DeleteAnnotationErrors[keyof DeleteAnnotationErrors];

export type DeleteAnnotationResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PatchAnnotationData = {
  body: PatchAnnotationRequest;
  path: {
    /**
     * File Id
     */
    file_id: string;
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{file_id}/annotations/{id}";
};

export type PatchAnnotationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PatchAnnotationError =
  PatchAnnotationErrors[keyof PatchAnnotationErrors];

export type PatchAnnotationResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileThumbnailData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/thumbnail";
};

export type GetFileThumbnailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileThumbnailError =
  GetFileThumbnailErrors[keyof GetFileThumbnailErrors];

export type GetFileThumbnailResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/tags";
};

export type ListTagsResponses = {
  /**
   * Response Listtags
   *
   * Successful Response
   */
  200: Array<TagWithDetailsResponse>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type UpdateTagData = {
  body: UpdateTagRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/tags/{id}";
};

export type UpdateTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListAuthorsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/authors";
};

export type ListAuthorsResponses = {
  /**
   * Response Listauthors
   *
   * Successful Response
   */
  200: Array<AuthorResponse>;
};

export type ListAuthorsResponse =
  ListAuthorsResponses[keyof ListAuthorsResponses];

export type SearchFilesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page Index
     *
     * Page index
     */
    page_index?: number;
    /**
     * Page Size
     *
     * Number of items per page
     */
    page_size?: number;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Authors
     */
    authors?: Array<string> | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Annotation
     */
    annotation?: string | null;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Status
     */
    status?: FileStatusEnum | null;
  };
  url: "/api/v1/search/files";
};

export type SearchFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchFilesError = SearchFilesErrors[keyof SearchFilesErrors];

export type SearchFilesResponses = {
  /**
   * Response Searchfiles
   *
   * Successful Response
   */
  200: Array<FileSearchResponse>;
};

export type SearchFilesResponse =
  SearchFilesResponses[keyof SearchFilesResponses];

export type GetAppStateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/setup/state";
};

export type GetAppStateResponses = {
  /**
   * Successful Response
   */
  200: AppStateResponse;
};

export type GetAppStateResponse =
  GetAppStateResponses[keyof GetAppStateResponses];

export type CreateSetupUserData = {
  body: SetupUserWritable;
  path?: never;
  query?: never;
  url: "/api/v1/setup/user";
};

export type CreateSetupUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSetupUserError =
  CreateSetupUserErrors[keyof CreateSetupUserErrors];

export type CreateSetupUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type CreateSetupUserResponse =
  CreateSetupUserResponses[keyof CreateSetupUserResponses];

export type GetAppStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/setup/status";
};

export type GetAppStatusResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateUserAccountDetailsData = {
  body: DetailsUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/account/details";
};

export type UpdateUserAccountDetailsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserAccountDetailsError =
  UpdateUserAccountDetailsErrors[keyof UpdateUserAccountDetailsErrors];

export type UpdateUserAccountDetailsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateUserPasswordData = {
  body: CredentialsUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/account/password";
};

export type UpdateUserPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserPasswordError =
  UpdateUserPasswordErrors[keyof UpdateUserPasswordErrors];

export type UpdateUserPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListPersonalApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/account/keys";
};

export type ListPersonalApiKeysResponses = {
  /**
   * Response Listpersonalapikeys
   *
   * Successful Response
   */
  200: Array<ApiKeyResponse>;
};

export type ListPersonalApiKeysResponse =
  ListPersonalApiKeysResponses[keyof ListPersonalApiKeysResponses];

export type CreatePersonalApiKeyData = {
  body: ApiKeyPersonalCreate;
  path?: never;
  query?: never;
  url: "/api/v1/account/keys";
};

export type CreatePersonalApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePersonalApiKeyError =
  CreatePersonalApiKeyErrors[keyof CreatePersonalApiKeyErrors];

export type CreatePersonalApiKeyResponses = {
  /**
   * Successful Response
   */
  200: ApiKeyCreateResultResponse;
};

export type CreatePersonalApiKeyResponse =
  CreatePersonalApiKeyResponses[keyof CreatePersonalApiKeyResponses];

export type RevokePersonalApiKeyData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/account/keys/{id}";
};

export type RevokePersonalApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RevokePersonalApiKeyError =
  RevokePersonalApiKeyErrors[keyof RevokePersonalApiKeyErrors];

export type RevokePersonalApiKeyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResetPersonalApiKeyData = {
  body: ApiKeyResetRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/account/keys/{id}/reset";
};

export type ResetPersonalApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetPersonalApiKeyError =
  ResetPersonalApiKeyErrors[keyof ResetPersonalApiKeyErrors];

export type ResetPersonalApiKeyResponses = {
  /**
   * Successful Response
   */
  200: ApiKeyCreateResultResponse;
};

export type ResetPersonalApiKeyResponse =
  ResetPersonalApiKeyResponses[keyof ResetPersonalApiKeyResponses];

export type ListRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/roles";
};

export type ListRolesResponses = {
  /**
   * Response Listroles
   *
   * Successful Response
   */
  200: Array<RoleResponse>;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/users";
};

export type ListUsersResponses = {
  /**
   * Response Listusers
   *
   * Successful Response
   */
  200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: UserCreateRequestWritable;
  path?: never;
  query?: never;
  url: "/api/v1/identity/users";
};

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/users/{id}";
};

export type DeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateUserData = {
  body: UserUpdateRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/users/{id}";
};

export type UpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResetUserPasswordData = {
  body: CredentialsReset;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/users/{id}/password";
};

export type ResetUserPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetUserPasswordError =
  ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListAuthProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/auth_providers";
};

export type ListAuthProvidersResponses = {
  /**
   * Response Listauthproviders
   *
   * Successful Response
   */
  200: Array<AuthProviderResponse>;
};

export type ListAuthProvidersResponse =
  ListAuthProvidersResponses[keyof ListAuthProvidersResponses];

export type ListOidcAuthProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc";
};

export type ListOidcAuthProvidersResponses = {
  /**
   * Response Listoidcauthproviders
   *
   * Successful Response
   */
  200: Array<AuthProviderOidcResponse>;
};

export type ListOidcAuthProvidersResponse =
  ListOidcAuthProvidersResponses[keyof ListOidcAuthProvidersResponses];

export type CreateOidcAuthProviderData = {
  body: AuthProviderOidcCreateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc";
};

export type CreateOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOidcAuthProviderError =
  CreateOidcAuthProviderErrors[keyof CreateOidcAuthProviderErrors];

export type CreateOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteOidcAuthProviderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc/{id}";
};

export type DeleteOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteOidcAuthProviderError =
  DeleteOidcAuthProviderErrors[keyof DeleteOidcAuthProviderErrors];

export type DeleteOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOidcAuthProviderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc/{id}";
};

export type GetOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOidcAuthProviderError =
  GetOidcAuthProviderErrors[keyof GetOidcAuthProviderErrors];

export type GetOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: AuthProviderOidcResponse;
};

export type GetOidcAuthProviderResponse =
  GetOidcAuthProviderResponses[keyof GetOidcAuthProviderResponses];

export type UpdateOidcAuthProviderData = {
  body: AuthProviderOidcUpdateRequestWritable;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc/{id}";
};

export type UpdateOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateOidcAuthProviderError =
  UpdateOidcAuthProviderErrors[keyof UpdateOidcAuthProviderErrors];

export type UpdateOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetApiDocsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/general/api/docs";
};

export type GetApiDocsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/general/api/keys";
};

export type ListApiKeysResponses = {
  /**
   * Response Listapikeys
   *
   * Successful Response
   */
  200: Array<ApiKeyResponse>;
};

export type ListApiKeysResponse =
  ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
  body: ApiKeyCreateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/general/api/keys";
};

export type CreateApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
  /**
   * Successful Response
   */
  200: ApiKeyCreateResultResponse;
};

export type CreateApiKeyResponse =
  CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type RevokeApiKeyData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/general/api/keys/{id}";
};

export type RevokeApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResetApiKeyData = {
  body: ApiKeyResetRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/general/api/keys/{id}/reset";
};

export type ResetApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetApiKeyError = ResetApiKeyErrors[keyof ResetApiKeyErrors];

export type ResetApiKeyResponses = {
  /**
   * Successful Response
   */
  200: ApiKeyCreateResultResponse;
};

export type ResetApiKeyResponse =
  ResetApiKeyResponses[keyof ResetApiKeyResponses];

export type ListActiveTasksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/general/tasks/active";
};

export type ListActiveTasksResponses = {
  /**
   * Response Listactivetasks
   *
   * Successful Response
   */
  200: Array<TaskActiveResponse>;
};

export type ListActiveTasksResponse =
  ListActiveTasksResponses[keyof ListActiveTasksResponses];

export type ListTaskHistoryData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page Index
     *
     * Page index
     */
    page_index?: number;
    /**
     * Page Size
     *
     * Number of items per page
     */
    page_size?: number;
  };
  url: "/api/v1/general/tasks/history";
};

export type ListTaskHistoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTaskHistoryError =
  ListTaskHistoryErrors[keyof ListTaskHistoryErrors];

export type ListTaskHistoryResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseTaskHistoryResponse;
};

export type ListTaskHistoryResponse =
  ListTaskHistoryResponses[keyof ListTaskHistoryResponses];

export type OpdsRootData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/opds/";
};

export type OpdsRootResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpdsAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/opds/all";
};

export type OpdsAllResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpdsOpenSearchData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/opds/opensearch.xml";
};

export type OpdsOpenSearchResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpdsSearchData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     */
    q?: string;
  };
  url: "/api/v1/opds/search";
};

export type OpdsSearchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpdsSearchError = OpdsSearchErrors[keyof OpdsSearchErrors];

export type OpdsSearchResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpdsShelfData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/opds/shelf";
};

export type OpdsShelfResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpdsCollectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/opds/collections";
};

export type OpdsCollectionsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpdsCollectionData = {
  body?: never;
  path: {
    /**
     * Collection Id
     */
    collection_id: string;
  };
  query?: never;
  url: "/api/v1/opds/collections/{collection_id}";
};

export type OpdsCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpdsCollectionError =
  OpdsCollectionErrors[keyof OpdsCollectionErrors];

export type OpdsCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOpdsFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
    /**
     * Ext
     */
    ext: string;
  };
  query?: never;
  url: "/api/v1/opds/file/{id}.{ext}";
};

export type GetOpdsFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOpdsFileError = GetOpdsFileErrors[keyof GetOpdsFileErrors];

export type GetOpdsFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOpdsFileThumbnailData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/opds/file/{id}/thumbnail";
};

export type GetOpdsFileThumbnailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOpdsFileThumbnailError =
  GetOpdsFileThumbnailErrors[keyof GetOpdsFileThumbnailErrors];

export type GetOpdsFileThumbnailResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
