// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5173" | (string & {});
};

/**
 * AccessToken
 *
 * API access token.
 */
export type AccessToken = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
  /**
   * Expires
   */
  expires: Date;
};

/**
 * AppStateResponse
 */
export type AppStateResponse = {
  /**
   * Is Initial User Created
   */
  is_initial_user_created?: boolean;
  /**
   * Sso Servers
   */
  sso_servers?: Array<SsoConfigResponse>;
  auto_login_sso_server?: SsoConfigResponse | null;
  /**
   * Is Setup Complete
   *
   * Check if the setup is complete
   */
  readonly is_setup_complete: boolean;
};

/**
 * AuthProviderOidcCreateRequest
 */
export type AuthProviderOidcCreateRequest = {
  /**
   * Name
   */
  name: string;
};

/**
 * AuthProviderOidcResponse
 */
export type AuthProviderOidcResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Entity Type
   */
  entity_type: "OIDC";
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
  /**
   * Group Claim Name
   */
  group_claim_name: string;
  /**
   * Auto Discovery Url
   */
  auto_discovery_url: string;
  /**
   * Additional Scopes
   */
  additional_scopes: string;
  /**
   * Auto Login
   */
  auto_login: boolean;
  /**
   * Group Claim Rules
   */
  group_claim_rules: Array<OidcGroupRuleOutput>;
  /**
   * Redirect Url
   *
   * URL to which the OIDC provider will redirect after successful authentication
   */
  redirect_url: string;
  /**
   * Authorize Url
   *
   * URL to which the frontend should redirect the user to initiate OIDC authentication
   */
  authorize_url: string;
};

/**
 * AuthProviderOidcUpdateRequest
 */
export type AuthProviderOidcUpdateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Is Enabled
   */
  is_enabled?: boolean;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Auto Discovery Url
   */
  auto_discovery_url: string;
  /**
   * Additional Scopes
   */
  additional_scopes?: string;
  /**
   * Group Claim Name
   *
   * Claim name providing group names
   */
  group_claim_name?: string;
  /**
   * Group Claim Rules
   */
  group_claim_rules?: Array<OidcGroupRuleInput>;
  /**
   * Auto Login
   */
  auto_login?: boolean;
};

/**
 * AuthProviderResponse
 *
 * Generic response model for authentication providers.
 *
 * Specific provider types may have additional parameters, but all share these common parameters.
 */
export type AuthProviderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Is Protected
   */
  is_protected: boolean;
};

/**
 * Body_CreateAuthToken
 */
export type BodyCreateAuthToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * Body_UploadFile
 */
export type BodyUploadFile = {
  /**
   * File
   */
  file: Blob | File;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Folder Id
   */
  folder_id: string;
  /**
   * Tags
   */
  tags?: Array<string>;
};

/**
 * CollectionResponse
 */
export type CollectionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * CreateCollectionRequest
 */
export type CreateCollectionRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * CreateFolderRequest
 */
export type CreateFolderRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * CredentialsReset
 *
 * This model is used to reset (by admin) user credentials.
 */
export type CredentialsReset = {
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
};

/**
 * CredentialsUpdate
 *
 * This model is used to change user credentials.
 */
export type CredentialsUpdate = {
  /**
   * Password Old
   */
  password_old: string;
  /**
   * Password New
   */
  password_new: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
};

/**
 * DetailsUpdate
 */
export type DetailsUpdate = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * FileResponse
 */
export type FileResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Folder Id
   */
  folder_id?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<TagResponse>;
  /**
   * Is Favorite
   */
  is_favorite: boolean;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Current Page
   */
  current_page: number;
  /**
   * Scale
   */
  scale: string;
  /**
   * Tags Name List
   */
  readonly tags_name_list: Array<string>;
};

/**
 * FolderResponse
 */
export type FolderResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Files
   */
  files?: Array<FileResponse>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LibraryTreeNode
 */
export type LibraryTreeNode = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Children
   */
  children?: Array<LibraryTreeNode>;
  /**
   * Entity Type
   */
  entity_type: "collection" | "folder";
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * OidcGroupRule
 */
export type OidcGroupRuleInput = {
  /**
   * Group
   *
   * Name of the group as provided by the OIDC provider
   */
  group: string;
  /**
   * Role Id
   *
   * ID of the role to assign to users in this group
   */
  role_id: string;
};

/**
 * OidcGroupRule
 */
export type OidcGroupRuleOutput = {
  /**
   * Group
   *
   * Name of the group as provided by the OIDC provider
   */
  group: string;
  /**
   * Role Id
   *
   * ID of the role to assign to users in this group
   */
  role_id: string;
};

/**
 * PatchFileStateRequest
 */
export type PatchFileStateRequest = {
  /**
   * Current Page
   */
  current_page?: number | null;
  /**
   * Scale
   */
  scale?: string | null;
};

/**
 * RevokeResponse
 */
export type RevokeResponse = {
  /**
   * Redirect Url
   */
  redirect_url?: string | null;
};

/**
 * RoleResponse
 */
export type RoleResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Scopes
   */
  scopes: string;
  /**
   * Scope List
   */
  readonly scope_list: Array<string>;
};

/**
 * SetupUser
 *
 * Create initial application user
 */
export type SetupUser = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * SsoConfigResponse
 */
export type SsoConfigResponse = {
  /**
   * Url
   */
  url: string;
  /**
   * Is Auto Login Enabled
   */
  is_auto_login_enabled: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * TagDetailResponse
 */
export type TagDetailResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
  /**
   * File Count
   */
  file_count: number;
};

/**
 * TagResponse
 */
export type TagResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
};

/**
 * UpdateCollectionRequest
 */
export type UpdateCollectionRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * UpdateFileRequest
 */
export type UpdateFileRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Folder Id
   */
  folder_id?: string | null;
  /**
   * Is Favorite
   */
  is_favorite?: boolean;
};

/**
 * UpdateFolderRequest
 */
export type UpdateFolderRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
};

/**
 * UpdateTagRequest
 */
export type UpdateTagRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
};

/**
 * UserCreateRequest
 */
export type UserCreateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Auth Provider Id
   */
  auth_provider_id: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
  role: RoleResponse;
  /**
   * Is External
   */
  is_external: boolean;
  auth_provider: AuthProviderResponse;
};

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export type UserSessionResponse = {
  /**
   * User Id
   */
  user_id: string;
  user: UserResponse;
  /**
   * Session Id
   */
  session_id: string;
};

/**
 * UserUpdateRequest
 */
export type UserUpdateRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * AppStateResponse
 */
export type AppStateResponseWritable = {
  /**
   * Is Initial User Created
   */
  is_initial_user_created?: boolean;
  /**
   * Sso Servers
   */
  sso_servers?: Array<SsoConfigResponse>;
  auto_login_sso_server?: SsoConfigResponse | null;
};

/**
 * AuthProviderOidcUpdateRequest
 */
export type AuthProviderOidcUpdateRequestWritable = {
  /**
   * Name
   */
  name: string;
  /**
   * Is Enabled
   */
  is_enabled?: boolean;
  /**
   * Client Id
   */
  client_id: string;
  /**
   * Client Secret
   */
  client_secret: string;
  /**
   * Auto Discovery Url
   */
  auto_discovery_url: string;
  /**
   * Additional Scopes
   */
  additional_scopes?: string;
  /**
   * Group Claim Name
   *
   * Claim name providing group names
   */
  group_claim_name?: string;
  /**
   * Group Claim Rules
   */
  group_claim_rules?: Array<OidcGroupRuleInput>;
  /**
   * Auto Login
   */
  auto_login?: boolean;
};

/**
 * FileResponse
 */
export type FileResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Folder Id
   */
  folder_id?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Tags
   */
  tags?: Array<TagResponse>;
  /**
   * Is Favorite
   */
  is_favorite: boolean;
  /**
   * Page Count
   */
  page_count: number;
  /**
   * Current Page
   */
  current_page: number;
  /**
   * Scale
   */
  scale: string;
};

/**
 * FolderResponse
 */
export type FolderResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Parent Id
   */
  parent_id?: string | null;
  /**
   * Files
   */
  files?: Array<FileResponseWritable>;
};

/**
 * RoleResponse
 */
export type RoleResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Is Protected
   */
  is_protected: boolean;
  /**
   * Entity Type
   */
  entity_type: string;
  /**
   * Scopes
   */
  scopes: string;
};

/**
 * SetupUser
 *
 * Create initial application user
 */
export type SetupUserWritable = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
  /**
   * Name
   */
  name: string;
};

/**
 * UserCreateRequest
 */
export type UserCreateRequestWritable = {
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Password Confirm
   */
  password_confirm: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
};

/**
 * UserResponse
 */
export type UserResponseWritable = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Auth Provider Id
   */
  auth_provider_id: string;
  /**
   * Is Enabled
   */
  is_enabled: boolean;
  /**
   * Role Id
   */
  role_id: string;
  role: RoleResponseWritable;
  /**
   * Is External
   */
  is_external: boolean;
  auth_provider: AuthProviderResponse;
};

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export type UserSessionResponseWritable = {
  /**
   * User Id
   */
  user_id: string;
  user: UserResponseWritable;
  /**
   * Session Id
   */
  session_id: string;
};

export type GetCurrentSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/session";
};

export type GetCurrentSessionResponses = {
  /**
   * Successful Response
   */
  200: UserSessionResponse;
};

export type GetCurrentSessionResponse =
  GetCurrentSessionResponses[keyof GetCurrentSessionResponses];

export type RevokeTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type RevokeTokenResponses = {
  /**
   * Successful Response
   */
  200: RevokeResponse;
};

export type RevokeTokenResponse =
  RevokeTokenResponses[keyof RevokeTokenResponses];

export type CreateAuthTokenData = {
  body: BodyCreateAuthToken;
  path?: never;
  query?: never;
  url: "/api/v1/auth/token";
};

export type CreateAuthTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAuthTokenError =
  CreateAuthTokenErrors[keyof CreateAuthTokenErrors];

export type CreateAuthTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type CreateAuthTokenResponse =
  CreateAuthTokenResponses[keyof CreateAuthTokenResponses];

export type RefreshAuthTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/refresh";
};

export type RefreshAuthTokenResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type RefreshAuthTokenResponse =
  RefreshAuthTokenResponses[keyof RefreshAuthTokenResponses];

export type OidcLoginData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/auth/oidc/{id}";
};

export type OidcLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OidcLoginError = OidcLoginErrors[keyof OidcLoginErrors];

export type OidcLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OidcCallbackData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/auth/oidc/{id}/callback";
};

export type OidcCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OidcCallbackError = OidcCallbackErrors[keyof OidcCallbackErrors];

export type ListCollectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/collections";
};

export type ListCollectionsResponses = {
  /**
   * Response Listcollections
   *
   * Successful Response
   */
  200: Array<CollectionResponse>;
};

export type ListCollectionsResponse =
  ListCollectionsResponses[keyof ListCollectionsResponses];

export type CreateCollectionData = {
  body: CreateCollectionRequest;
  path?: never;
  query?: never;
  url: "/api/v1/library/collections";
};

export type CreateCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCollectionError =
  CreateCollectionErrors[keyof CreateCollectionErrors];

export type CreateCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteCollectionData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type DeleteCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCollectionError =
  DeleteCollectionErrors[keyof DeleteCollectionErrors];

export type DeleteCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateCollectionData = {
  body: UpdateCollectionRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/collections/{id}";
};

export type UpdateCollectionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCollectionError =
  UpdateCollectionErrors[keyof UpdateCollectionErrors];

export type UpdateCollectionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteFolderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/folders/{id}";
};

export type DeleteFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFolderError = DeleteFolderErrors[keyof DeleteFolderErrors];

export type DeleteFolderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFolderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/folders/{id}";
};

export type GetFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFolderError = GetFolderErrors[keyof GetFolderErrors];

export type GetFolderResponses = {
  /**
   * Successful Response
   */
  200: FolderResponse;
};

export type GetFolderResponse = GetFolderResponses[keyof GetFolderResponses];

export type UpdateFolderData = {
  body: UpdateFolderRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/folders/{id}";
};

export type UpdateFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFolderError = UpdateFolderErrors[keyof UpdateFolderErrors];

export type UpdateFolderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListFoldersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/folders";
};

export type ListFoldersResponses = {
  /**
   * Response Listfolders
   *
   * Successful Response
   */
  200: Array<FolderResponse>;
};

export type ListFoldersResponse =
  ListFoldersResponses[keyof ListFoldersResponses];

export type CreateFolderData = {
  body: CreateFolderRequest;
  path?: never;
  query?: never;
  url: "/api/v1/library/folders";
};

export type CreateFolderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type DeleteFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileDetailsData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type GetFileDetailsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileDetailsError =
  GetFileDetailsErrors[keyof GetFileDetailsErrors];

export type GetFileDetailsResponses = {
  /**
   * Successful Response
   */
  200: FileResponse;
};

export type GetFileDetailsResponse =
  GetFileDetailsResponses[keyof GetFileDetailsResponses];

export type UpdateFileData = {
  body: UpdateFileRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}";
};

export type UpdateFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateFileError = UpdateFileErrors[keyof UpdateFileErrors];

export type UpdateFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PatchFileStateData = {
  body: PatchFileStateRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/state";
};

export type PatchFileStateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PatchFileStateError =
  PatchFileStateErrors[keyof PatchFileStateErrors];

export type PatchFileStateResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetLibraryTreeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/tree";
};

export type GetLibraryTreeResponses = {
  /**
   * Response Getlibrarytree
   *
   * Successful Response
   */
  200: Array<LibraryTreeNode>;
};

export type GetLibraryTreeResponse =
  GetLibraryTreeResponses[keyof GetLibraryTreeResponses];

export type ListTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/tags";
};

export type ListTagsResponses = {
  /**
   * Response Listtags
   *
   * Successful Response
   */
  200: Array<TagDetailResponse>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type DeleteTagData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/tags/{id}";
};

export type DeleteTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateTagData = {
  body: UpdateTagRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/tags/{id}";
};

export type UpdateTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListUncategorizedFilesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/library/files/uncategorized";
};

export type ListUncategorizedFilesResponses = {
  /**
   * Response Listuncategorizedfiles
   *
   * Successful Response
   */
  200: Array<FileResponse>;
};

export type ListUncategorizedFilesResponse =
  ListUncategorizedFilesResponses[keyof ListUncategorizedFilesResponses];

export type ListFilesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Is Favorite
     */
    is_favorite?: boolean | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Names
     */
    names?: Array<string> | null;
    /**
     * Descriptions
     */
    descriptions?: Array<string> | null;
    /**
     * Text
     */
    text?: Array<string> | null;
  };
  url: "/api/v1/library/files";
};

export type ListFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
  /**
   * Response Listfiles
   *
   * Successful Response
   */
  200: Array<FileResponse>;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type UploadFileData = {
  body: BodyUploadFile;
  path?: never;
  query?: never;
  url: "/api/v1/library/files/upload";
};

export type UploadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFileData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/library/files/{id}/download";
};

export type GetFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAppStateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/setup/state";
};

export type GetAppStateResponses = {
  /**
   * Successful Response
   */
  200: AppStateResponse;
};

export type GetAppStateResponse =
  GetAppStateResponses[keyof GetAppStateResponses];

export type CreateSetupUserData = {
  body: SetupUserWritable;
  path?: never;
  query?: never;
  url: "/api/v1/setup/user";
};

export type CreateSetupUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSetupUserError =
  CreateSetupUserErrors[keyof CreateSetupUserErrors];

export type CreateSetupUserResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type CreateSetupUserResponse =
  CreateSetupUserResponses[keyof CreateSetupUserResponses];

export type GetAppStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/setup/status";
};

export type GetAppStatusResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateUserAccountDetailsData = {
  body: DetailsUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/account/details";
};

export type UpdateUserAccountDetailsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserAccountDetailsError =
  UpdateUserAccountDetailsErrors[keyof UpdateUserAccountDetailsErrors];

export type UpdateUserAccountDetailsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateUserPasswordData = {
  body: CredentialsUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/account/password";
};

export type UpdateUserPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserPasswordError =
  UpdateUserPasswordErrors[keyof UpdateUserPasswordErrors];

export type UpdateUserPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/roles";
};

export type ListRolesResponses = {
  /**
   * Response Listroles
   *
   * Successful Response
   */
  200: Array<RoleResponse>;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/users";
};

export type ListUsersResponses = {
  /**
   * Response Listusers
   *
   * Successful Response
   */
  200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: UserCreateRequestWritable;
  path?: never;
  query?: never;
  url: "/api/v1/identity/users";
};

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/users/{id}";
};

export type DeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateUserData = {
  body: UserUpdateRequest;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/users/{id}";
};

export type UpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResetUserPasswordData = {
  body: CredentialsReset;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/users/{id}/password";
};

export type ResetUserPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetUserPasswordError =
  ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListAuthProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/auth_providers";
};

export type ListAuthProvidersResponses = {
  /**
   * Response Listauthproviders
   *
   * Successful Response
   */
  200: Array<AuthProviderResponse>;
};

export type ListAuthProvidersResponse =
  ListAuthProvidersResponses[keyof ListAuthProvidersResponses];

export type ListOidcAuthProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc";
};

export type ListOidcAuthProvidersResponses = {
  /**
   * Response Listoidcauthproviders
   *
   * Successful Response
   */
  200: Array<AuthProviderOidcResponse>;
};

export type ListOidcAuthProvidersResponse =
  ListOidcAuthProvidersResponses[keyof ListOidcAuthProvidersResponses];

export type CreateOidcAuthProviderData = {
  body: AuthProviderOidcCreateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc";
};

export type CreateOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOidcAuthProviderError =
  CreateOidcAuthProviderErrors[keyof CreateOidcAuthProviderErrors];

export type CreateOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteOidcAuthProviderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc/{id}";
};

export type DeleteOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteOidcAuthProviderError =
  DeleteOidcAuthProviderErrors[keyof DeleteOidcAuthProviderErrors];

export type DeleteOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOidcAuthProviderData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc/{id}";
};

export type GetOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOidcAuthProviderError =
  GetOidcAuthProviderErrors[keyof GetOidcAuthProviderErrors];

export type GetOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: AuthProviderOidcResponse;
};

export type GetOidcAuthProviderResponse =
  GetOidcAuthProviderResponses[keyof GetOidcAuthProviderResponses];

export type UpdateOidcAuthProviderData = {
  body: AuthProviderOidcUpdateRequestWritable;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/identity/auth_providers/oidc/{id}";
};

export type UpdateOidcAuthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateOidcAuthProviderError =
  UpdateOidcAuthProviderErrors[keyof UpdateOidcAuthProviderErrors];

export type UpdateOidcAuthProviderResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
