// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * AccessToken
 *
 * API access token.
 */
export const zAccessToken = z.object({
  access_token: z.string(),
  token_type: z.string(),
  expires: z.iso.datetime(),
});

/**
 * AppStateResponse
 */
export const zAppStateResponse = z.object({
  is_initial_user_created: z.boolean().optional().default(false),
  is_setup_complete: z.boolean().readonly(),
});

/**
 * AuthProviderResponse
 */
export const zAuthProviderResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  description: z.string().nullish(),
  entity_type: z.string(),
  is_enabled: z.boolean(),
  is_protected: z.boolean(),
});

/**
 * Body_CreateAuthToken
 */
export const zBodyCreateAuthToken = z.object({
  grant_type: z
    .string()
    .regex(/^password$/)
    .nullish(),
  username: z.string(),
  password: z.string(),
  scope: z.string().optional().default(""),
  client_id: z.string().nullish(),
  client_secret: z.string().nullish(),
});

/**
 * Body_UploadFile
 */
export const zBodyUploadFile = z.object({
  file: z.string(),
  name: z.string(),
  description: z.string().nullish(),
  folder_id: z.uuid(),
  tags: z.array(z.string()).optional(),
});

/**
 * CollectionResponse
 */
export const zCollectionResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  parent_id: z.uuid().nullish(),
});

/**
 * CreateCollectionRequest
 */
export const zCreateCollectionRequest = z.object({
  name: z.string(),
  parent_id: z.uuid().nullish(),
});

/**
 * CreateFolderRequest
 */
export const zCreateFolderRequest = z.object({
  name: z.string(),
  parent_id: z.uuid().nullish(),
});

/**
 * CredentialsUpdate
 *
 * This model is used to change user credentials.
 */
export const zCredentialsUpdate = z.object({
  password_old: z.string(),
  password_new: z.string(),
  password_confirm: z.string(),
});

/**
 * DetailsUpdate
 */
export const zDetailsUpdate = z.object({
  email: z.string(),
  name: z.string(),
});

/**
 * LibraryTreeNode
 */
export const zLibraryTreeNode = z.object({
  id: z.uuid(),
  name: z.string(),
  children: z.array(z.lazy((): any => zLibraryTreeNode)).optional(),
  entity_type: z.enum(["collection", "folder"]),
  parent_id: z.uuid().nullish(),
});

/**
 * PatchFileStateRequest
 */
export const zPatchFileStateRequest = z.object({
  current_page: z.int().gte(1).nullish(),
  scale: z.string().nullish(),
});

/**
 * RoleResponse
 */
export const zRoleResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  description: z.string(),
  is_protected: z.boolean(),
  entity_type: z.string(),
  scopes: z.string(),
  scope_list: z.array(z.string()).readonly(),
});

/**
 * SetupUser
 *
 * Create initial application user
 */
export const zSetupUser = z.object({
  email: z.string(),
  name: z.string(),
});

/**
 * TagDetailResponse
 */
export const zTagDetailResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  color: z.string(),
  file_count: z.int(),
});

/**
 * TagResponse
 */
export const zTagResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  color: z.string(),
});

/**
 * FileResponse
 */
export const zFileResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  folder_id: z.uuid().nullish(),
  description: z.string().nullish(),
  tags: z.array(zTagResponse).optional(),
  is_favorite: z.boolean(),
  page_count: z.int(),
  current_page: z.int(),
  scale: z.string(),
  tags_name_list: z.array(z.string()).readonly(),
});

/**
 * FolderResponse
 */
export const zFolderResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  parent_id: z.uuid().nullish(),
  files: z.array(zFileResponse).optional(),
});

/**
 * UpdateCollectionRequest
 */
export const zUpdateCollectionRequest = z.object({
  name: z.string(),
  parent_id: z.uuid().nullish(),
});

/**
 * UpdateFileRequest
 */
export const zUpdateFileRequest = z.object({
  name: z.string().min(1).max(255),
  description: z.string().max(255).nullish(),
  tags: z.array(z.string()).optional(),
  folder_id: z.uuid().nullish(),
  is_favorite: z.boolean().optional().default(false),
});

/**
 * UpdateFolderRequest
 */
export const zUpdateFolderRequest = z.object({
  name: z.string(),
  parent_id: z.uuid().nullish(),
});

/**
 * UpdateTagRequest
 */
export const zUpdateTagRequest = z.object({
  name: z.string(),
  color: z.string(),
});

/**
 * UserResponse
 */
export const zUserResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.string(),
  auth_provider_id: z.uuid(),
  is_enabled: z.boolean(),
  role_id: z.uuid(),
  role: zRoleResponse,
  auth_provider: zAuthProviderResponse,
});

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export const zUserSessionResponse = z.object({
  user_id: z.uuid(),
  user: zUserResponse,
  session_id: z.uuid(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * AppStateResponse
 */
export const zAppStateResponseWritable = z.object({
  is_initial_user_created: z.boolean().optional().default(false),
});

/**
 * FileResponse
 */
export const zFileResponseWritable = z.object({
  id: z.uuid(),
  name: z.string(),
  folder_id: z.uuid().nullish(),
  description: z.string().nullish(),
  tags: z.array(zTagResponse).optional(),
  is_favorite: z.boolean(),
  page_count: z.int(),
  current_page: z.int(),
  scale: z.string(),
});

/**
 * FolderResponse
 */
export const zFolderResponseWritable = z.object({
  id: z.uuid(),
  name: z.string(),
  parent_id: z.uuid().nullish(),
  files: z.array(zFileResponseWritable).optional(),
});

/**
 * RoleResponse
 */
export const zRoleResponseWritable = z.object({
  id: z.uuid(),
  name: z.string(),
  description: z.string(),
  is_protected: z.boolean(),
  entity_type: z.string(),
  scopes: z.string(),
});

/**
 * SetupUser
 *
 * Create initial application user
 */
export const zSetupUserWritable = z.object({
  email: z.string(),
  password: z.string(),
  password_confirm: z.string(),
  name: z.string(),
});

/**
 * UserResponse
 */
export const zUserResponseWritable = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.string(),
  auth_provider_id: z.uuid(),
  is_enabled: z.boolean(),
  role_id: z.uuid(),
  role: zRoleResponseWritable,
  auth_provider: zAuthProviderResponse,
});

/**
 * UserSessionResponse
 *
 * Provides relevant information about the logged-in user. Should not include authentication data.
 */
export const zUserSessionResponseWritable = z.object({
  user_id: z.uuid(),
  user: zUserResponseWritable,
  session_id: z.uuid(),
});

export const zGetCurrentSessionData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetCurrentSessionResponse = zUserSessionResponse;

export const zRevokeTokenData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zCreateAuthTokenData = z.object({
  body: zBodyCreateAuthToken,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zCreateAuthTokenResponse = zAccessToken;

export const zRefreshAuthTokenData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zRefreshAuthTokenResponse = zAccessToken;

export const zListCollectionsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Listcollections
 *
 * Successful Response
 */
export const zListCollectionsResponse = z.array(zCollectionResponse);

export const zCreateCollectionData = z.object({
  body: zCreateCollectionRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zDeleteCollectionData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zUpdateCollectionData = z.object({
  body: zUpdateCollectionRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zDeleteFolderData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zGetFolderData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetFolderResponse = zFolderResponse;

export const zUpdateFolderData = z.object({
  body: zUpdateFolderRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zListFoldersData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Listfolders
 *
 * Successful Response
 */
export const zListFoldersResponse = z.array(zFolderResponse);

export const zCreateFolderData = z.object({
  body: zCreateFolderRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zDeleteFileData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zGetFileDetailsData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetFileDetailsResponse = zFileResponse;

export const zUpdateFileData = z.object({
  body: zUpdateFileRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zPatchFileStateData = z.object({
  body: zPatchFileStateRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zGetLibraryTreeData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Getlibrarytree
 *
 * Successful Response
 */
export const zGetLibraryTreeResponse = z.array(zLibraryTreeNode);

export const zListTagsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Listtags
 *
 * Successful Response
 */
export const zListTagsResponse = z.array(zTagDetailResponse);

export const zDeleteTagData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zUpdateTagData = z.object({
  body: zUpdateTagRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zListUncategorizedFilesData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Listuncategorizedfiles
 *
 * Successful Response
 */
export const zListUncategorizedFilesResponse = z.array(zFileResponse);

export const zListFilesData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      is_favorite: z.boolean().nullish(),
      tags: z.array(z.string()).nullish(),
      names: z.array(z.string()).nullish(),
      descriptions: z.array(z.string()).nullish(),
      text: z.array(z.string()).nullish(),
    })
    .optional(),
});

/**
 * Response Listfiles
 *
 * Successful Response
 */
export const zListFilesResponse = z.array(zFileResponse);

export const zUploadFileData = z.object({
  body: zBodyUploadFile,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetFileData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.never().optional(),
});

export const zGetAppStateData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetAppStateResponse = zAppStateResponse;

export const zCreateSetupUserData = z.object({
  body: zSetupUserWritable,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zCreateSetupUserResponse = zUserResponse;

export const zGetAppStatusData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zUpdateUserAccountDetailsData = z.object({
  body: zDetailsUpdate,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zUpdateUserPasswordData = z.object({
  body: zCredentialsUpdate,
  path: z.never().optional(),
  query: z.never().optional(),
});
