"""empty message

Revision ID: 2f9c004cb3ff
Revises: d3620788bbe2
Create Date: 2026-08-23 09:24:14.845990

"""

# TODO DEV

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f9c004cb3ff"
down_revision: Union[str, None] = "d3620788bbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=False, server_default="unread"))

    with op.batch_alter_table("file_states", schema=None) as batch_op:
        batch_op.alter_column("status", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_states", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
