"""oidc

Revision ID: 8e49615039a4
Revises: d8a333667539
Create Date: 2026-04-09 18:31:02.951046

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e49615039a4"
down_revision: Union[str, None] = "d8a333667539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_providers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("client_secret", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("auto_discovery_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("additional_scopes", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("group_claim_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("group_claim_rules", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("auto_login", sa.Boolean(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_external", sa.Boolean(), nullable=False, server_default=sa.text("false")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_external")

    with op.batch_alter_table("auth_providers", schema=None) as batch_op:
        batch_op.drop_column("auto_login")
        batch_op.drop_column("group_claim_rules")
        batch_op.drop_column("group_claim_name")
        batch_op.drop_column("additional_scopes")
        batch_op.drop_column("auto_discovery_url")
        batch_op.drop_column("client_secret")
        batch_op.drop_column("client_id")

    # ### end Alembic commands ###
