"""tasks & authors

Revision ID: d3620788bbe2
Revises: c8afa0f76ca2
Create Date: 2026-08-01 20:41:36.027376

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from server.const import SessionTypeEnum
from server.infrastructure.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "d3620788bbe2"
down_revision: Union[str, None] = "c8afa0f76ca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("name", name=op.f("uq_authors_name")),
    )
    op.create_table(
        "task_runs",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("started_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("finished_at", DateTimeUTC(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_runs")),
    )
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_runs_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_runs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("dedup_key", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)

    op.create_table(
        "file_authors",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["authors.id"], name=op.f("fk_file_authors_author_id_authors"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_authors_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("file_id", "author_id", "id", name=op.f("pk_file_authors")),
    )
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at", DateTimeUTC(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at", DateTimeUTC(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")
            )
        )

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("thumbnail_content_type", sa.String(), nullable=False, server_default="image/webp")
        )
        batch_op.add_column(sa.Column("published", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("original_name", sa.String(), nullable=False, server_default=""))
        batch_op.add_column(
            sa.Column(
                "created_at", DateTimeUTC(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at", DateTimeUTC(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")
            )
        )
        batch_op.alter_column("thumbnail", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("session_type", sa.String(), nullable=False, server_default=SessionTypeEnum.INTERACTIVE.value)
        )
        batch_op.add_column(sa.Column("revoked_at", DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("scopes", sa.String(), nullable=True))
        batch_op.alter_column("auth_provider_id", existing_type=sa.CHAR(length=32), nullable=False)
        batch_op.drop_constraint(batch_op.f("fk_sessions_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_sessions_auth_provider_id_auth_providers"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_auth_provider_id_auth_providers"),
            "auth_providers",
            ["auth_provider_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_user_id_users"), "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    op.execute(
        sa.text("UPDATE files SET original_name = CASE WHEN lower(name) LIKE '%.pdf' THEN name ELSE name || '.pdf' END")
    )

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.alter_column("session_type", server_default=None)

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("thumbnail_content_type", server_default=None)
        batch_op.alter_column("created_at", server_default=None)
        batch_op.alter_column("updated_at", server_default=None)
        batch_op.alter_column("original_name", server_default=None)

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.alter_column("created_at", server_default=None)
        batch_op.alter_column("updated_at", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_sessions_user_id_users"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_sessions_auth_provider_id_auth_providers"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_auth_provider_id_auth_providers"),
            "auth_providers",
            ["auth_provider_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_user_id_users"), "users", ["user_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.alter_column("auth_provider_id", existing_type=sa.CHAR(length=32), nullable=True)
        batch_op.drop_column("scopes")
        batch_op.drop_column("description")
        batch_op.drop_column("revoked_at")
        batch_op.drop_column("session_type")

    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("thumbnail", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("original_name")
        batch_op.drop_column("published")
        batch_op.drop_column("thumbnail_content_type")

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    op.drop_table("file_authors")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_dedup_key"))

    op.drop_table("tasks")
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_runs_name"))

    op.drop_table("task_runs")
    op.drop_table("authors")
    # ### end Alembic commands ###
