"""empty message

Revision ID: 965005be7067
Revises: 87d25fb9a8d6
Create Date: 2026-07-26 20:47:34.902733

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from server.infrastructure.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "965005be7067"
down_revision: Union[str, None] = "87d25fb9a8d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at", DateTimeUTC(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at", DateTimeUTC(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")
            )
        )

    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.alter_column("created_at", server_default=None)
        batch_op.alter_column("updated_at", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
