"""empty message

Revision ID: e3f4c2193f79
Revises: 2aba5ff8069b
Create Date: 2026-07-11 19:49:12.135638

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from server.infrastructure.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "e3f4c2193f79"
down_revision: Union[str, None] = "2aba5ff8069b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_runs",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("finished_at", DateTimeUTC(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_runs")),
    )
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_runs_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_runs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("dedup_key", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_dedup_key"))

    op.drop_table("tasks")
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_runs_name"))

    op.drop_table("task_runs")
    # ### end Alembic commands ###
