"""empty message

Revision ID: 48227513f372
Revises: b68ad229d088
Create Date: 2026-09-14 08:33:38.352709

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48227513f372"
down_revision: Union[str, None] = "b68ad229d088"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_identifiers",
        sa.Column("scheme", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_identifiers_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_identifiers")),
        sa.UniqueConstraint("file_id", "scheme", name="unique_file_identifier"),
    )
    with op.batch_alter_table("file_identifiers", schema=None) as batch_op:
        batch_op.create_index("ix_file_identifiers_lookup", ["scheme", "value"], unique=False)

    with op.batch_alter_table("file_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extra", sa.JSON(), nullable=False, server_default="{}"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_states", schema=None) as batch_op:
        batch_op.drop_column("extra")

    with op.batch_alter_table("file_identifiers", schema=None) as batch_op:
        batch_op.drop_index("ix_file_identifiers_lookup")

    op.drop_table("file_identifiers")
    # ### end Alembic commands ###
