"""empty message

Revision ID: 07d213c43a0a
Revises: 965005be7067
Create Date: 2026-07-28 21:46:56.981301

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07d213c43a0a"
down_revision: Union[str, None] = "965005be7067"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("thumbnail", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("thumbnail", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
