"""empty message

Revision ID: b68ad229d088
Revises: 2f9c004cb3ff
Create Date: 2026-09-06 16:54:06.245764

"""

import json
from collections.abc import Callable, Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b68ad229d088"
down_revision: Union[str, None] = "2f9c004cb3ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCOPE_TABLES = ["roles", "sessions"]

LIBRARY_SCOPES_MAP = {
    "user:read": "library:read",
    "user:write": "library:write",
}


def _rewrite_scopes(convert: Callable[[str], str], tables: list[str]):
    bind = op.get_bind()

    for table in tables:
        rows = bind.execute(sa.text(f"SELECT id, scopes FROM {table} WHERE scopes IS NOT NULL")).fetchall()

        for row_id, scopes in rows:
            updated = convert(scopes)

            if updated == scopes:
                continue

            bind.execute(
                sa.text(f"UPDATE {table} SET scopes = :scopes WHERE id = :id"),
                {"scopes": updated, "id": row_id},
            )


def _to_json_array(scopes: str) -> str:
    # Already converted
    if scopes.startswith("["):
        return scopes

    return json.dumps([scope for scope in scopes.split(" ") if scope])


def _to_scope_string(scopes: str) -> str:
    if not scopes.startswith("["):
        return scopes

    return " ".join(json.loads(scopes))


def _grant_library_scopes(current: str) -> str:
    sc = json.loads(current)
    implied = [LIBRARY_SCOPES_MAP[scope] for scope in sc if scope in LIBRARY_SCOPES_MAP]
    sc = sc + [scope for scope in implied if scope not in sc]
    return json.dumps(sc)


def _revoke_library_scopes(current: str) -> str:
    revoked = set(LIBRARY_SCOPES_MAP.values())
    return json.dumps([scope for scope in json.loads(current) if scope not in revoked])


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _rewrite_scopes(_to_json_array, SCOPE_TABLES)
    _rewrite_scopes(_grant_library_scopes, SCOPE_TABLES)

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column("scopes", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=False)

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.alter_column("scopes", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.alter_column("scopes", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=True)

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column("scopes", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=False)

    _rewrite_scopes(_revoke_library_scopes, SCOPE_TABLES)
    _rewrite_scopes(_to_scope_string, SCOPE_TABLES)

    # ### end Alembic commands ###
