"""api key

Revision ID: ac574b18923e
Revises: c8afa0f76ca2
Create Date: 2026-06-13 14:39:33.839859

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from server.const import SessionTypeEnum
from server.infrastructure.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "ac574b18923e"
down_revision: Union[str, None] = "c8afa0f76ca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("session_type", sa.String(), nullable=False, server_default=SessionTypeEnum.INTERACTIVE.value)
        )
        batch_op.add_column(sa.Column("revoked_at", DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("scopes", sa.String(), nullable=True))
        batch_op.alter_column("auth_provider_id", existing_type=sa.CHAR(length=32), nullable=False)
        batch_op.drop_constraint(batch_op.f("fk_sessions_auth_provider_id_auth_providers"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_sessions_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_user_id_users"), "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_auth_provider_id_auth_providers"),
            "auth_providers",
            ["auth_provider_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.alter_column("session_type", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_sessions_auth_provider_id_auth_providers"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_sessions_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_user_id_users"), "users", ["user_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_sessions_auth_provider_id_auth_providers"),
            "auth_providers",
            ["auth_provider_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.alter_column("auth_provider_id", existing_type=sa.CHAR(length=32), nullable=True)
        batch_op.drop_column("scopes")
        batch_op.drop_column("description")
        batch_op.drop_column("revoked_at")
        batch_op.drop_column("session_type")

    # ### end Alembic commands ###
