"""initial

Revision ID: d8a333667539
Revises:
Create Date: 2026-03-27 16:48:30.314809

"""

from collections.abc import Sequence
from typing import Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

from server.const import AuthProviderTypesEnum, RolesEnum, ScopesEnum
from server.infrastructure.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "d8a333667539"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    providers = op.create_table(
        "auth_providers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="unique_provider_name"),
    )
    roles = op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="role", nullable=False),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="unique_role_name"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.LargeBinary(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="user", nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("auth_provider_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["auth_provider_id"], ["auth_providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="unique_user_email"),
    )
    op.create_table(
        "collections",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("expires_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="session", nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("auth_provider_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["auth_provider_id"], ["auth_providers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="unique_tag"),
    )
    op.create_table(
        "folders",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("current_page", sa.Integer(), nullable=False),
        sa.Column("scale", sa.String(), nullable=False),
        sa.Column("file_storage", sa.String(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_tags",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "tag_id"),
    )

    op.bulk_insert(
        roles,
        [
            {
                "id": uuid4(),
                "name": RolesEnum.ADMIN,
                "description": "Full access to all features and functionalities",
                "is_protected": True,
                "scopes": " ".join(
                    [ScopesEnum.ADMIN_READ, ScopesEnum.ADMIN_WRITE, ScopesEnum.USER_READ, ScopesEnum.USER_WRITE]
                ),
            },
            {
                "id": uuid4(),
                "name": RolesEnum.USER,
                "description": "Basic access for app usage, allowing reading and writing user-related data",
                "is_protected": True,
                "scopes": " ".join([ScopesEnum.USER_READ, ScopesEnum.USER_WRITE]),
            },
            {
                "id": uuid4(),
                "name": RolesEnum.AUDIT,
                "description": "Read-only access",
                "is_protected": True,
                "scopes": " ".join([ScopesEnum.USER_READ, ScopesEnum.ADMIN_READ]),
            },
        ],
    )

    op.bulk_insert(
        providers,
        [
            {
                "id": uuid4(),
                "name": "LOCAL",
                "entity_type": AuthProviderTypesEnum.LOCAL,
                "description": "Authenticate users using LOCAL database",
                "is_protected": True,
                "is_enabled": True,
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_tags")
    op.drop_table("files")
    op.drop_table("folders")
    op.drop_table("tags")
    op.drop_table("sessions")
    op.drop_table("collections")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("auth_providers")
    # ### end Alembic commands ###
