"""empty message

Revision ID: 2aba5ff8069b
Revises: ac574b18923e
Create Date: 2026-06-29 18:04:04.271359

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2aba5ff8069b"
down_revision: Union[str, None] = "ac574b18923e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("name", name=op.f("uq_authors_name")),
    )
    op.create_table(
        "file_authors",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["authors.id"], name=op.f("fk_file_authors_author_id_authors"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_authors_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("file_id", "author_id", "id", name=op.f("pk_file_authors")),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("published", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_column("published")

    op.drop_table("file_authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
