"""initial

Revision ID: c8afa0f76ca2
Revises:
Create Date: 2026-04-19 20:05:27.876938

"""

from collections.abc import Sequence
from typing import Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

from server.const import AuthProviderTypesEnum, RolesEnum, ScopesEnum
from server.infrastructure.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "c8afa0f76ca2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    providers = op.create_table(
        "auth_providers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("client_secret", sa.String(), nullable=True),
        sa.Column("auto_discovery_url", sa.String(), nullable=True),
        sa.Column("additional_scopes", sa.String(), nullable=True),
        sa.Column("group_claim_name", sa.String(), nullable=True),
        sa.Column("group_claim_rules", sa.JSON(), nullable=True),
        sa.Column("auto_login", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_providers")),
        sa.UniqueConstraint("name", name=op.f("uq_auth_providers_name")),
    )
    op.create_table(
        "collections",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.Enum("folder", "group", native_enum=False), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["collections.id"], name=op.f("fk_collections_parent_id_collections"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    roles = op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="role", nullable=False),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "files",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("thumbnail", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], name=op.f("fk_files_collection_id_collections"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.LargeBinary(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="user", nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("auth_provider_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auth_provider_id"],
            ["auth_providers.id"],
            name=op.f("fk_users_auth_provider_id_auth_providers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "file_states",
        sa.Column("current_page", sa.Integer(), nullable=False),
        sa.Column("scale", sa.String(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_states_file_id_files"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_file_states_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_states")),
    )
    op.create_table(
        "file_tags",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], name=op.f("fk_file_tags_file_id_files"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_file_tags_tag_id_tags"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "tag_id", "id", name=op.f("pk_file_tags")),
    )
    op.create_table(
        "resource_permissions",
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission", sa.Enum("owner", "read", "modify", native_enum=False), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resource_permissions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_permissions")),
        sa.UniqueConstraint("resource_id", "user_id", name="unique_permission"),
    )
    op.create_table(
        "sessions",
        sa.Column("expires_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("entity_type", sa.String(), server_default="session", nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("auth_provider_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auth_provider_id"],
            ["auth_providers.id"],
            name=op.f("fk_sessions_auth_provider_id_auth_providers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "user_tag_preferences",
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_user_tag_preferences_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_tag_preferences_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tag_id", "user_id", "id", name=op.f("pk_user_tag_preferences")),
    )

    op.execute(
        sa.text("""
    CREATE VIRTUAL TABLE IF NOT EXISTS content_fts USING fts5(
        content,
        doc_id UNINDEXED,
        entity_type UNINDEXED,
        page_number UNINDEXED,
        fragment_type UNINDEXED
    )
    """)
    )

    op.execute(
        sa.text("""
    CREATE TRIGGER delete_collection_permissions
    AFTER DELETE ON collections
    FOR EACH ROW
    BEGIN
        DELETE FROM resource_permissions WHERE resource_id = OLD.id;
    END;
    """)
    )
    op.execute(
        sa.text("""
    CREATE TRIGGER delete_file_cascade
    AFTER DELETE ON files
    FOR EACH ROW
    BEGIN
        DELETE FROM resource_permissions WHERE resource_id = OLD.id;
        DELETE FROM content_fts WHERE doc_id = OLD.id;
    END;
    """)
    )

    op.bulk_insert(
        roles,
        [
            {
                "id": uuid4(),
                "name": RolesEnum.ADMIN,
                "description": "Full access to all features and functionalities",
                "is_protected": True,
                "scopes": " ".join(
                    [ScopesEnum.ADMIN_READ, ScopesEnum.ADMIN_WRITE, ScopesEnum.USER_READ, ScopesEnum.USER_WRITE]
                ),
            },
            {
                "id": uuid4(),
                "name": RolesEnum.USER,
                "description": "Basic access for app usage, allowing reading and writing user-related data",
                "is_protected": True,
                "scopes": " ".join([ScopesEnum.USER_READ, ScopesEnum.USER_WRITE]),
            },
            {
                "id": uuid4(),
                "name": RolesEnum.AUDIT,
                "description": "Read-only access",
                "is_protected": True,
                "scopes": " ".join([ScopesEnum.USER_READ, ScopesEnum.ADMIN_READ]),
            },
        ],
    )

    op.bulk_insert(
        providers,
        [
            {
                "id": uuid4(),
                "name": "LOCAL",
                "entity_type": AuthProviderTypesEnum.LOCAL,
                "description": "Authenticate users using LOCAL database",
                "is_protected": True,
                "is_enabled": True,
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tag_preferences")
    op.drop_table("sessions")
    op.drop_table("resource_permissions")
    op.drop_table("file_tags")
    op.drop_table("file_states")
    op.drop_table("users")
    op.drop_table("files")
    op.drop_table("tags")
    op.drop_table("roles")
    op.drop_table("collections")
    op.drop_table("auth_providers")
    op.drop_table("content_fts_config")
    op.drop_table("content_fts_data")
    op.drop_table("content_fts_content")
    op.drop_table("content_fts_idx")
    op.drop_table("content_fts")
    op.drop_table("content_fts_docsize")
    # ### end Alembic commands ###
