"""empty message

Revision ID: 5fe9fef19b5b
Revises: e3f4c2193f79
Create Date: 2026-07-16 20:57:39.932942

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe9fef19b5b'
down_revision: Union[str, None] = 'e3f4c2193f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('subject')

    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###