// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createAuthToken,
  createCollection,
  createFolder,
  createOidcAuthProvider,
  createSetupUser,
  createUser,
  deleteCollection,
  deleteFile,
  deleteFolder,
  deleteOidcAuthProvider,
  deleteTag,
  deleteUser,
  getAppState,
  getAppStatus,
  getCurrentSession,
  getFile,
  getFileDetails,
  getFolder,
  getLibraryTree,
  getOidcAuthProvider,
  listAuthProviders,
  listCollections,
  listFiles,
  listFolders,
  listOidcAuthProviders,
  listRoles,
  listTags,
  listUncategorizedFiles,
  listUsers,
  oidcCallback,
  oidcLogin,
  type Options,
  patchFileState,
  refreshAuthToken,
  resetUserPassword,
  revokeToken,
  updateCollection,
  updateFile,
  updateFolder,
  updateOidcAuthProvider,
  updateTag,
  updateUser,
  updateUserAccountDetails,
  updateUserPassword,
  uploadFile,
} from "../sdk.gen";
import type {
  CreateAuthTokenData,
  CreateAuthTokenError,
  CreateAuthTokenResponse,
  CreateCollectionData,
  CreateCollectionError,
  CreateFolderData,
  CreateFolderError,
  CreateOidcAuthProviderData,
  CreateOidcAuthProviderError,
  CreateSetupUserData,
  CreateSetupUserError,
  CreateSetupUserResponse,
  CreateUserData,
  CreateUserError,
  DeleteCollectionData,
  DeleteCollectionError,
  DeleteFileData,
  DeleteFileError,
  DeleteFolderData,
  DeleteFolderError,
  DeleteOidcAuthProviderData,
  DeleteOidcAuthProviderError,
  DeleteTagData,
  DeleteTagError,
  DeleteUserData,
  DeleteUserError,
  GetAppStateData,
  GetAppStateResponse,
  GetAppStatusData,
  GetCurrentSessionData,
  GetCurrentSessionResponse,
  GetFileData,
  GetFileDetailsData,
  GetFileDetailsError,
  GetFileDetailsResponse,
  GetFileError,
  GetFolderData,
  GetFolderError,
  GetFolderResponse,
  GetLibraryTreeData,
  GetLibraryTreeResponse,
  GetOidcAuthProviderData,
  GetOidcAuthProviderError,
  GetOidcAuthProviderResponse,
  ListAuthProvidersData,
  ListAuthProvidersResponse,
  ListCollectionsData,
  ListCollectionsResponse,
  ListFilesData,
  ListFilesError,
  ListFilesResponse,
  ListFoldersData,
  ListFoldersResponse,
  ListOidcAuthProvidersData,
  ListOidcAuthProvidersResponse,
  ListRolesData,
  ListRolesResponse,
  ListTagsData,
  ListTagsResponse,
  ListUncategorizedFilesData,
  ListUncategorizedFilesResponse,
  ListUsersData,
  ListUsersResponse,
  OidcCallbackData,
  OidcCallbackError,
  OidcLoginData,
  OidcLoginError,
  PatchFileStateData,
  PatchFileStateError,
  RefreshAuthTokenData,
  RefreshAuthTokenResponse,
  ResetUserPasswordData,
  ResetUserPasswordError,
  RevokeTokenData,
  RevokeTokenResponse,
  UpdateCollectionData,
  UpdateCollectionError,
  UpdateFileData,
  UpdateFileError,
  UpdateFolderData,
  UpdateFolderError,
  UpdateOidcAuthProviderData,
  UpdateOidcAuthProviderError,
  UpdateTagData,
  UpdateTagError,
  UpdateUserAccountDetailsData,
  UpdateUserAccountDetailsError,
  UpdateUserData,
  UpdateUserError,
  UpdateUserPasswordData,
  UpdateUserPasswordError,
  UploadFileData,
  UploadFileError,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getCurrentSessionQueryKey = (
  options?: Options<GetCurrentSessionData>,
) => createQueryKey("getCurrentSession", options);

/**
 * Get Current Session
 *
 * Get information about the current user session.
 */
export const getCurrentSessionOptions = (
  options?: Options<GetCurrentSessionData>,
) =>
  queryOptions<
    GetCurrentSessionResponse,
    DefaultError,
    GetCurrentSessionResponse,
    ReturnType<typeof getCurrentSessionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrentSessionQueryKey(options),
  });

/**
 * Revoke Token
 *
 * Invalidate the access and refresh tokens
 */
export const revokeTokenMutation = (
  options?: Partial<Options<RevokeTokenData>>,
): UseMutationOptions<
  RevokeTokenResponse,
  DefaultError,
  Options<RevokeTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    RevokeTokenResponse,
    DefaultError,
    Options<RevokeTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Authenticate With Password
 *
 * Create access and refresh tokens using Basic Auth.
 */
export const createAuthTokenMutation = (
  options?: Partial<Options<CreateAuthTokenData>>,
): UseMutationOptions<
  CreateAuthTokenResponse,
  CreateAuthTokenError,
  Options<CreateAuthTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAuthTokenResponse,
    CreateAuthTokenError,
    Options<CreateAuthTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAuthToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh Token
 *
 * Receive a new access token using the refresh token.
 */
export const refreshAuthTokenMutation = (
  options?: Partial<Options<RefreshAuthTokenData>>,
): UseMutationOptions<
  RefreshAuthTokenResponse,
  DefaultError,
  Options<RefreshAuthTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshAuthTokenResponse,
    DefaultError,
    Options<RefreshAuthTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshAuthToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const oidcLoginQueryKey = (options: Options<OidcLoginData>) =>
  createQueryKey("oidcLogin", options);

/**
 * Oidc Authorize
 */
export const oidcLoginOptions = (options: Options<OidcLoginData>) =>
  queryOptions<
    unknown,
    OidcLoginError,
    unknown,
    ReturnType<typeof oidcLoginQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await oidcLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: oidcLoginQueryKey(options),
  });

export const oidcCallbackQueryKey = (options: Options<OidcCallbackData>) =>
  createQueryKey("oidcCallback", options);

/**
 * Oidc Callback
 */
export const oidcCallbackOptions = (options: Options<OidcCallbackData>) =>
  queryOptions<
    unknown,
    OidcCallbackError,
    unknown,
    ReturnType<typeof oidcCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await oidcCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: oidcCallbackQueryKey(options),
  });

export const listCollectionsQueryKey = (
  options?: Options<ListCollectionsData>,
) => createQueryKey("listCollections", options);

/**
 * List Collections
 */
export const listCollectionsOptions = (
  options?: Options<ListCollectionsData>,
) =>
  queryOptions<
    ListCollectionsResponse,
    DefaultError,
    ListCollectionsResponse,
    ReturnType<typeof listCollectionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCollections({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listCollectionsQueryKey(options),
  });

/**
 * Create Collection
 */
export const createCollectionMutation = (
  options?: Partial<Options<CreateCollectionData>>,
): UseMutationOptions<
  unknown,
  CreateCollectionError,
  Options<CreateCollectionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateCollectionError,
    Options<CreateCollectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCollection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Collection
 */
export const deleteCollectionMutation = (
  options?: Partial<Options<DeleteCollectionData>>,
): UseMutationOptions<
  unknown,
  DeleteCollectionError,
  Options<DeleteCollectionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteCollectionError,
    Options<DeleteCollectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteCollection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Collection
 */
export const updateCollectionMutation = (
  options?: Partial<Options<UpdateCollectionData>>,
): UseMutationOptions<
  unknown,
  UpdateCollectionError,
  Options<UpdateCollectionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateCollectionError,
    Options<UpdateCollectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateCollection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Folder
 */
export const deleteFolderMutation = (
  options?: Partial<Options<DeleteFolderData>>,
): UseMutationOptions<
  unknown,
  DeleteFolderError,
  Options<DeleteFolderData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteFolderError,
    Options<DeleteFolderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteFolder({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFolderQueryKey = (options: Options<GetFolderData>) =>
  createQueryKey("getFolder", options);

/**
 * Get Folder
 */
export const getFolderOptions = (options: Options<GetFolderData>) =>
  queryOptions<
    GetFolderResponse,
    GetFolderError,
    GetFolderResponse,
    ReturnType<typeof getFolderQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFolder({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFolderQueryKey(options),
  });

/**
 * Update Folder
 */
export const updateFolderMutation = (
  options?: Partial<Options<UpdateFolderData>>,
): UseMutationOptions<
  unknown,
  UpdateFolderError,
  Options<UpdateFolderData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateFolderError,
    Options<UpdateFolderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateFolder({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listFoldersQueryKey = (options?: Options<ListFoldersData>) =>
  createQueryKey("listFolders", options);

/**
 * List Folders
 */
export const listFoldersOptions = (options?: Options<ListFoldersData>) =>
  queryOptions<
    ListFoldersResponse,
    DefaultError,
    ListFoldersResponse,
    ReturnType<typeof listFoldersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFolders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFoldersQueryKey(options),
  });

/**
 * Create Folder
 */
export const createFolderMutation = (
  options?: Partial<Options<CreateFolderData>>,
): UseMutationOptions<
  unknown,
  CreateFolderError,
  Options<CreateFolderData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateFolderError,
    Options<CreateFolderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createFolder({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete File
 */
export const deleteFileMutation = (
  options?: Partial<Options<DeleteFileData>>,
): UseMutationOptions<unknown, DeleteFileError, Options<DeleteFileData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteFileError,
    Options<DeleteFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFileDetailsQueryKey = (options: Options<GetFileDetailsData>) =>
  createQueryKey("getFileDetails", options);

/**
 * Get File Details
 */
export const getFileDetailsOptions = (options: Options<GetFileDetailsData>) =>
  queryOptions<
    GetFileDetailsResponse,
    GetFileDetailsError,
    GetFileDetailsResponse,
    ReturnType<typeof getFileDetailsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFileDetails({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFileDetailsQueryKey(options),
  });

/**
 * Update File
 */
export const updateFileMutation = (
  options?: Partial<Options<UpdateFileData>>,
): UseMutationOptions<unknown, UpdateFileError, Options<UpdateFileData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateFileError,
    Options<UpdateFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Patch File State
 */
export const patchFileStateMutation = (
  options?: Partial<Options<PatchFileStateData>>,
): UseMutationOptions<
  unknown,
  PatchFileStateError,
  Options<PatchFileStateData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PatchFileStateError,
    Options<PatchFileStateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchFileState({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getLibraryTreeQueryKey = (options?: Options<GetLibraryTreeData>) =>
  createQueryKey("getLibraryTree", options);

/**
 * Get Library Tree
 */
export const getLibraryTreeOptions = (options?: Options<GetLibraryTreeData>) =>
  queryOptions<
    GetLibraryTreeResponse,
    DefaultError,
    GetLibraryTreeResponse,
    ReturnType<typeof getLibraryTreeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLibraryTree({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLibraryTreeQueryKey(options),
  });

export const listTagsQueryKey = (options?: Options<ListTagsData>) =>
  createQueryKey("listTags", options);

/**
 * List Tags
 */
export const listTagsOptions = (options?: Options<ListTagsData>) =>
  queryOptions<
    ListTagsResponse,
    DefaultError,
    ListTagsResponse,
    ReturnType<typeof listTagsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTags({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTagsQueryKey(options),
  });

/**
 * Delete Tag
 */
export const deleteTagMutation = (
  options?: Partial<Options<DeleteTagData>>,
): UseMutationOptions<unknown, DeleteTagError, Options<DeleteTagData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteTagError,
    Options<DeleteTagData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTag({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Tag
 */
export const updateTagMutation = (
  options?: Partial<Options<UpdateTagData>>,
): UseMutationOptions<unknown, UpdateTagError, Options<UpdateTagData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateTagError,
    Options<UpdateTagData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTag({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listUncategorizedFilesQueryKey = (
  options?: Options<ListUncategorizedFilesData>,
) => createQueryKey("listUncategorizedFiles", options);

/**
 * List Uncategorized Files
 */
export const listUncategorizedFilesOptions = (
  options?: Options<ListUncategorizedFilesData>,
) =>
  queryOptions<
    ListUncategorizedFilesResponse,
    DefaultError,
    ListUncategorizedFilesResponse,
    ReturnType<typeof listUncategorizedFilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUncategorizedFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUncategorizedFilesQueryKey(options),
  });

export const listFilesQueryKey = (options?: Options<ListFilesData>) =>
  createQueryKey("listFiles", options);

/**
 * List Files
 */
export const listFilesOptions = (options?: Options<ListFilesData>) =>
  queryOptions<
    ListFilesResponse,
    ListFilesError,
    ListFilesResponse,
    ReturnType<typeof listFilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFilesQueryKey(options),
  });

/**
 * Upload File
 */
export const uploadFileMutation = (
  options?: Partial<Options<UploadFileData>>,
): UseMutationOptions<unknown, UploadFileError, Options<UploadFileData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UploadFileError,
    Options<UploadFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFileQueryKey = (options: Options<GetFileData>) =>
  createQueryKey("getFile", options);

/**
 * Get File
 */
export const getFileOptions = (options: Options<GetFileData>) =>
  queryOptions<
    unknown,
    GetFileError,
    unknown,
    ReturnType<typeof getFileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFileQueryKey(options),
  });

export const getAppStateQueryKey = (options?: Options<GetAppStateData>) =>
  createQueryKey("getAppState", options);

/**
 * State
 *
 * Get current app state
 */
export const getAppStateOptions = (options?: Options<GetAppStateData>) =>
  queryOptions<
    GetAppStateResponse,
    DefaultError,
    GetAppStateResponse,
    ReturnType<typeof getAppStateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAppState({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAppStateQueryKey(options),
  });

/**
 * Setup User
 *
 * Create initial app admin user
 */
export const createSetupUserMutation = (
  options?: Partial<Options<CreateSetupUserData>>,
): UseMutationOptions<
  CreateSetupUserResponse,
  CreateSetupUserError,
  Options<CreateSetupUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSetupUserResponse,
    CreateSetupUserError,
    Options<CreateSetupUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSetupUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAppStatusQueryKey = (options?: Options<GetAppStatusData>) =>
  createQueryKey("getAppStatus", options);

/**
 * Status
 *
 * liveness / readiness probe
 */
export const getAppStatusOptions = (options?: Options<GetAppStatusData>) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getAppStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAppStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAppStatusQueryKey(options),
  });

/**
 * Update Details
 *
 * Update current user's details.
 */
export const updateUserAccountDetailsMutation = (
  options?: Partial<Options<UpdateUserAccountDetailsData>>,
): UseMutationOptions<
  unknown,
  UpdateUserAccountDetailsError,
  Options<UpdateUserAccountDetailsData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateUserAccountDetailsError,
    Options<UpdateUserAccountDetailsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUserAccountDetails({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Password
 *
 * Update current user's password.
 */
export const updateUserPasswordMutation = (
  options?: Partial<Options<UpdateUserPasswordData>>,
): UseMutationOptions<
  unknown,
  UpdateUserPasswordError,
  Options<UpdateUserPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateUserPasswordError,
    Options<UpdateUserPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUserPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listRolesQueryKey = (options?: Options<ListRolesData>) =>
  createQueryKey("listRoles", options);

/**
 * List Roles
 */
export const listRolesOptions = (options?: Options<ListRolesData>) =>
  queryOptions<
    ListRolesResponse,
    DefaultError,
    ListRolesResponse,
    ReturnType<typeof listRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listRolesQueryKey(options),
  });

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
  createQueryKey("listUsers", options);

/**
 * List Users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) =>
  queryOptions<
    ListUsersResponse,
    DefaultError,
    ListUsersResponse,
    ReturnType<typeof listUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUsersQueryKey(options),
  });

/**
 * Create User
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<unknown, CreateUserError, Options<CreateUserData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete User
 */
export const deleteUserMutation = (
  options?: Partial<Options<DeleteUserData>>,
): UseMutationOptions<unknown, DeleteUserError, Options<DeleteUserData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserError,
    Options<DeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update User
 */
export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
): UseMutationOptions<unknown, UpdateUserError, Options<UpdateUserData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset User Password
 */
export const resetUserPasswordMutation = (
  options?: Partial<Options<ResetUserPasswordData>>,
): UseMutationOptions<
  unknown,
  ResetUserPasswordError,
  Options<ResetUserPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ResetUserPasswordError,
    Options<ResetUserPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await resetUserPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listAuthProvidersQueryKey = (
  options?: Options<ListAuthProvidersData>,
) => createQueryKey("listAuthProviders", options);

/**
 * List Providers
 */
export const listAuthProvidersOptions = (
  options?: Options<ListAuthProvidersData>,
) =>
  queryOptions<
    ListAuthProvidersResponse,
    DefaultError,
    ListAuthProvidersResponse,
    ReturnType<typeof listAuthProvidersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAuthProviders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAuthProvidersQueryKey(options),
  });

export const listOidcAuthProvidersQueryKey = (
  options?: Options<ListOidcAuthProvidersData>,
) => createQueryKey("listOidcAuthProviders", options);

/**
 * List Oidc Providers
 */
export const listOidcAuthProvidersOptions = (
  options?: Options<ListOidcAuthProvidersData>,
) =>
  queryOptions<
    ListOidcAuthProvidersResponse,
    DefaultError,
    ListOidcAuthProvidersResponse,
    ReturnType<typeof listOidcAuthProvidersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listOidcAuthProviders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listOidcAuthProvidersQueryKey(options),
  });

/**
 * Create Provider Oidc
 */
export const createOidcAuthProviderMutation = (
  options?: Partial<Options<CreateOidcAuthProviderData>>,
): UseMutationOptions<
  unknown,
  CreateOidcAuthProviderError,
  Options<CreateOidcAuthProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateOidcAuthProviderError,
    Options<CreateOidcAuthProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createOidcAuthProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Oidc Provider
 */
export const deleteOidcAuthProviderMutation = (
  options?: Partial<Options<DeleteOidcAuthProviderData>>,
): UseMutationOptions<
  unknown,
  DeleteOidcAuthProviderError,
  Options<DeleteOidcAuthProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteOidcAuthProviderError,
    Options<DeleteOidcAuthProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteOidcAuthProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOidcAuthProviderQueryKey = (
  options: Options<GetOidcAuthProviderData>,
) => createQueryKey("getOidcAuthProvider", options);

/**
 * Get Oidc Provider
 */
export const getOidcAuthProviderOptions = (
  options: Options<GetOidcAuthProviderData>,
) =>
  queryOptions<
    GetOidcAuthProviderResponse,
    GetOidcAuthProviderError,
    GetOidcAuthProviderResponse,
    ReturnType<typeof getOidcAuthProviderQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOidcAuthProvider({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOidcAuthProviderQueryKey(options),
  });

/**
 * Update Provider Oidc
 */
export const updateOidcAuthProviderMutation = (
  options?: Partial<Options<UpdateOidcAuthProviderData>>,
): UseMutationOptions<
  unknown,
  UpdateOidcAuthProviderError,
  Options<UpdateOidcAuthProviderData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateOidcAuthProviderError,
    Options<UpdateOidcAuthProviderData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateOidcAuthProvider({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
